export const SITE = {
  name: 'Dhab Pari',
  nameUrdu: 'ڈھاب پڑی',
  committee: 'Water & Welfare Committee',
  committeeUrdu: 'واٹر اینڈ ویلفیئر کمیٹی',
  taglineUrdu: 'ڈھاب پڑی واٹر اینڈ ویلفیئر کمیٹی - آپ کی خدمت، ہمارا مشن',
  whatsapp: '0333-5008575',
  whatsappLink: 'https://wa.me/923335008575',
  whatsappGroupLink: 'https://chat.whatsapp.com/EJicjqKIjUU8qEjKeRzHiR?s=sh&p=a&ilr=4',
  facebookLink: 'https://www.facebook.com/share/1JdVXFHyPz/',
  jazzcash: '0300-0000000',
  jazzcashName: 'Dhab Pari Welfare',
  easypaisa: '0345-0000000',
  easypaisaName: 'DP Welfare Committee',
  bankName: 'HBL',
  bankAccount: 'PK00 MCBA 0012 3456 7890 12',
  bankBranch: 'Dhab Pari Water & Welfare Branch',
  location: 'Dhab Pari, Dist. Chakwal, Punjab, Pakistan',
  established: '2018',
  domain: 'dhabpari.com',
  email: 'info@dhabpari.org',
  officeHours: 'Mon-Sat: 9AM-2PM, Fri: 9AM-12PM',
}
