'use client'

import { useEffect, useState, useCallback, useMemo } from 'react'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/client'
import { Search, FileText, Eye, Pencil, Trash2, SlidersHorizontal } from 'lucide-react'
import { billBadge, billBadgeClass, type BillBadgeTone } from '@/lib/billStatus'
import { donationBadge } from '@/lib/donationStatus'
import { useSystemAccess } from '@/hooks/useSystemAccess'
import { voucherReceiptKind, entryTypeLabel } from '@/lib/ledgerLabels'
import { ReceiptModal } from '@/components/admin/ReceiptModal'
import type { ReceiptData } from '@/components/admin/ReceiptDocument'
import { donorReceiptTotals } from '@/lib/donorReceiptTotals'
import { useLocale } from '@/lib/i18n/LocaleProvider'
import { fetchPeriodLockRule, dateIsLocked, DEFAULT_PERIOD_LOCK, type PeriodLockRule } from '@/lib/periodLock'
import { FilterSheet, FilterSheetSection, DateRangePillGroup } from '@/components/admin/FilterSheet'
import { SearchableField } from '@/components/admin/SearchablePicker'
import { presetRange, detectPreset, formatRangeLabel, presetLabelKey, PRESET_ORDER, today, monthStart, type DateRangePreset } from '@/lib/dateRangePresets'

type SystemTab = 'water_supply' | 'donors_projects'

interface TxnRow {
  id: string
  kind: 'bill' | 'payment' | 'voucher' | 'donation' | 'purchase'
  voucherType?: string
  borderColor: string
  typeLabel: string | null
  partyName: string
  docLabel: string
  date: string
  description: string
  amount: number
  badge: { text?: string; textKey?: string; tone: BillBadgeTone } | null
  note: string | null
  searchBlob: string
  billId?: string
  paymentId?: string
  voucherId?: string
  purchaseId?: string
  purchaseNumber?: string | null
  donationId?: string
  donationVoucherNo?: string | null
  donationVerified?: boolean
  // Generated by a recurring schedule rather than entered by hand.
  isRecurring?: boolean
  receiptNo?: string | null
  autoPosted?: boolean
  fullyApproved?: boolean
  createdAt: string
  // A multi-category voucher (Kafalat's monthly payment, a water_supply
  // multi-line expense) -- edit_voucher() refuses to touch these (migration
  // 175), so Edit is hidden rather than offered and rejected.
  hasLineItems?: boolean
  // Voucher rows only: the two accounts actually involved, shown as two
  // stacked lines (paid-to on top, paid-from underneath) instead of the
  // free-text party_name / generic type label the row used to lead with.
  voucherToName?: string
  voucherFromName?: string
  voucherNo?: string | null
}

const systemLabels: Record<SystemTab, string> = { water_supply: 'Water Supply System', donors_projects: 'Donors & Projects System' }

function fmtAmount(n: number) {
  return Number(n).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })
}

export default function AllTransactionsPage() {
  const { t, isUrdu } = useLocale()
  const access = useSystemAccess()
  const [system, setSystem] = useState<SystemTab>('water_supply')
  const [systemOverride] = useState<SystemTab | null>(() => {
    if (typeof window === 'undefined') return null
    const p = new URLSearchParams(window.location.search).get('system')
    return p === 'water_supply' || p === 'donors_projects' ? p : null
  })
  useEffect(() => {
    if (access.loading) return
    if (systemOverride === 'water_supply' && access.canWaterSupply) { setSystem('water_supply'); return }
    if (systemOverride === 'donors_projects' && access.canDonorsProjects) { setSystem('donors_projects'); return }
    setSystem(access.defaultSystem)
  }, [access.loading, access.defaultSystem, access.canWaterSupply, access.canDonorsProjects, systemOverride])
  const [from, setFrom] = useState(monthStart())
  const [to, setTo] = useState(today())
  const [statusFilter, setStatusFilter] = useState<'all' | 'paid' | 'partial' | 'pending' | 'overdue'>('all')
  const [kindFilter, setKindFilter] = useState('all')
  const [autoPostedOnly, setAutoPostedOnly] = useState(false)
  const [search, setSearch] = useState('')
  const [rows, setRows] = useState<TxnRow[]>([])
  const [viewReceipt, setViewReceipt] = useState<ReceiptData | null>(null)
  const [loading, setLoading] = useState(true)
  const [lockRule, setLockRule] = useState<PeriodLockRule>(DEFAULT_PERIOD_LOCK)
  const [showFilterSheet, setShowFilterSheet] = useState(false)
  const supabase = createClient()
  // Which preset pill (if any) the current from/to matches — derived, not
  // stored, so editing the date fields by hand and picking a pill never
  // fall out of sync with each other.
  const activePreset = useMemo(() => detectPreset(from, to), [from, to])
  const applyPreset = (key: DateRangePreset) => {
    if (key === 'custom') return
    const r = presetRange(key)
    setFrom(r.from); setTo(r.to)
  }

  useEffect(() => { fetchPeriodLockRule(supabase).then(setLockRule) }, [supabase])

  const load = useCallback(async () => {
    setLoading(true)
    const [consumersRes, billsRes, paymentsRes, vouchersRes, donationsRes, purchasesRes, autoPostedRes] = await Promise.all([
      system === 'water_supply'
        ? supabase.from('consumers').select('consumer_id, name, mobile')
        : Promise.resolve({ data: [] as { consumer_id: string; name: string; mobile: string }[] }),
      system === 'water_supply'
        ? supabase.from('bills').select('id, bill_number, consumer_id, month, year, amount_pkr, discount_amount, paid_amount, due_date, description, created_at, security_deposit_amount, security_deposit_voucher_id, recurring_schedule_id')
            .gte('created_at', from).lte('created_at', `${to}T23:59:59`)
        : Promise.resolve({ data: [] as { id: string; bill_number: string | null; consumer_id: string; month: number; year: number; amount_pkr: number; discount_amount: number | null; paid_amount: number | null; due_date: string | null; description: string | null; created_at: string; security_deposit_amount: number | null; security_deposit_voucher_id: string | null; recurring_schedule_id: string | null }[] }),
      system === 'water_supply'
        ? supabase.from('payments').select('id, bill_id, consumer_id, amount_pkr, method, paid_date, receipt_no, note, created_at').gte('paid_date', from).lte('paid_date', to)
        : Promise.resolve({ data: [] as { id: string; bill_id: string; consumer_id: string; amount_pkr: number; method: string | null; paid_date: string; receipt_no: string | null; note: string | null; created_at: string }[] }),
      supabase.from('vouchers').select('id, voucher_type, voucher_no, receipt_no, voucher_date, particular, amount_pkr, party_name, from_account_id, to_account_id, bill_id, created_at, recurring_schedule_id')
        .eq('system', system).in('status', ['posted', 'approved']).gte('voucher_date', from).lte('voucher_date', to),
      system === 'donors_projects'
        ? supabase.from('donors').select('id, name, amount_pkr, date, payment_method, notes, is_anonymous, created_at, voucher_no, is_verified, payment_status, recurring_schedule_id').gte('date', from).lte('date', to)
        : Promise.resolve({ data: [] as { id: string; name: string; amount_pkr: number; date: string; payment_method: string | null; notes: string | null; is_anonymous: boolean; created_at: string; voucher_no: string | null; is_verified: boolean; payment_status: string | null; recurring_schedule_id: string | null }[] }),
      system === 'water_supply'
        ? supabase.from('purchases').select('id, vendor, purchase_date, method, note, purchase_number, created_at').eq('system', system).eq('status', 'posted').gte('purchase_date', from).lte('purchase_date', to)
        : Promise.resolve({ data: [] as { id: string; vendor: string | null; purchase_date: string; method: string; note: string | null; purchase_number: string | null; created_at: string }[] }),
      // Auto-posted = the transaction went live after the 24-hour deadline
      // without every configured approver confirming (migration 060) — flagged
      // here so it can be surfaced/filtered separately from a normally-approved one.
      supabase.from('approval_requests').select('reference_id, auto_posted').eq('system', system).eq('status', 'posted'),
    ])
    const autoPostedIds = new Set((autoPostedRes.data ?? []).filter((r) => r.auto_posted).map((r) => r.reference_id))
    const fullyApprovedIds = new Set((autoPostedRes.data ?? []).filter((r) => !r.auto_posted).map((r) => r.reference_id))

    const consumersById = Object.fromEntries((consumersRes.data ?? []).map((c) => [c.consumer_id, c]))
    const billNumberById = Object.fromEntries((billsRes.data ?? []).map((b) => [b.id, b.bill_number]))
    // A security deposit collected with a bill posts as its own voucher for
    // real double-entry correctness, but it's the same cash-collection event —
    // fold its receipt info into the bill's row instead of showing it as an
    // unrelated third transaction.
    const depositReceiptByVoucherId = Object.fromEntries(
      (vouchersRes.data ?? []).filter((v) => v.voucher_type === 'security_deposit').map((v) => [v.id, v.receipt_no])
    )
    const voucherIdsForLines = (vouchersRes.data ?? []).map((v) => v.id)
    const { data: lineRows } = voucherIdsForLines.length > 0
      ? await supabase.from('voucher_line_items').select('voucher_id, account_id').in('voucher_id', voucherIdsForLines)
      : { data: [] as { voucher_id: string; account_id: string }[] }
    const voucherIdsWithLines = new Set((lineRows ?? []).map((l) => l.voucher_id))
    // voucher_line_items has no ordering column — this takes whichever line
    // comes back first per voucher, which in practice is insertion order
    // (a multi-line expense inserts all its lines in one bulk call, and
    // these rows are never reordered afterward). Good enough for a display
    // label; not something any real calculation depends on.
    const firstLineAccountIdByVoucher: Record<string, string> = {}
    for (const l of lineRows ?? []) { firstLineAccountIdByVoucher[l.voucher_id] ??= l.account_id }
    const accountIdsNeeded = new Set<string>()
    for (const v of vouchersRes.data ?? []) {
      if (v.from_account_id) accountIdsNeeded.add(v.from_account_id)
      if (v.to_account_id) accountIdsNeeded.add(v.to_account_id)
    }
    for (const id of Object.values(firstLineAccountIdByVoucher)) accountIdsNeeded.add(id)
    const { data: accountsForLabels } = accountIdsNeeded.size > 0
      ? await supabase.from('accounts').select('id, name, name_ur').in('id', Array.from(accountIdsNeeded))
      : { data: [] as { id: string; name: string; name_ur: string | null }[] }
    const accountNameById = Object.fromEntries(
      (accountsForLabels ?? []).map((a) => [a.id, isUrdu && a.name_ur ? a.name_ur : a.name])
    )
    const result: TxnRow[] = []

    for (const b of billsRes.data ?? []) {
      const net = Math.max(b.amount_pkr - (b.discount_amount ?? 0), 0)
      const consumer = consumersById[b.consumer_id]
      let description = b.description || `${t('tx.waterBillPrefix')} ${new Date(b.year, b.month - 1, 1).toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}`
      if (b.security_deposit_amount && b.security_deposit_amount > 0) {
        const receiptNo = b.security_deposit_voucher_id ? depositReceiptByVoucherId[b.security_deposit_voucher_id] : null
        description += ` ${t('tx.securityDepositSuffix')} ${fmtAmount(b.security_deposit_amount)}${receiptNo ? ` (${t('tx.receiptHashPrefix')} ${receiptNo})` : ''}`
      }
      result.push({
        id: `bill-${b.id}`, kind: 'bill', borderColor: 'border-emerald-500', isRecurring: !!b.recurring_schedule_id,
        typeLabel: null, partyName: consumer?.name ?? b.consumer_id,
        docLabel: b.bill_number ? `${t('tx.billHash')} ${b.bill_number}` : t('tx.billFallback'),
        date: b.due_date ?? new Date(b.year, b.month - 1, 1).toISOString().slice(0, 10),
        description, amount: net, badge: billBadge(b), note: null, billId: b.id, createdAt: b.created_at,
        searchBlob: `${consumer?.name ?? ''} ${b.consumer_id} ${consumer?.mobile ?? ''} ${b.bill_number ?? ''} ${b.description ?? ''}`.toLowerCase(),
      })
    }

    for (const p of paymentsRes.data ?? []) {
      const billNo = billNumberById[p.bill_id]
      const consumer = consumersById[p.consumer_id]
      result.push({
        id: `payment-${p.id}`, kind: 'payment', borderColor: 'border-cyan-500',
        typeLabel: p.method ? p.method.charAt(0).toUpperCase() + p.method.slice(1) : t('tx.cashFallback'),
        partyName: consumer?.name ?? p.consumer_id,
        docLabel: p.receipt_no ? `${t('tx.receiptHashPrefix')} ${p.receipt_no}` : t('tx.receiptFallback'),
        date: p.paid_date, description: billNo ? `${t('tx.againstBill')} ${billNo}` : (p.note || t('tx.paymentReceived')),
        amount: p.amount_pkr, badge: null, note: p.note, billId: p.bill_id, paymentId: p.id, receiptNo: p.receipt_no, createdAt: p.created_at,
        searchBlob: `${consumer?.name ?? ''} ${p.consumer_id} ${consumer?.mobile ?? ''} ${p.receipt_no ?? ''} ${p.method ?? ''} ${p.note ?? ''}`.toLowerCase(),
      })
    }

    for (const v of vouchersRes.data ?? []) {
      // Bill-linked security deposits are now folded into their bill's row above.
      if (v.voucher_type === 'security_deposit' && v.bill_id) continue
      const isSecurityDeposit = v.voucher_type === 'security_deposit'
      const label = entryTypeLabel('voucher', v.voucher_type, isUrdu ? 'ur' : 'en')
      // The generic "Voucher #" prefix told nobody what actually happened —
      // Purchases already lead with their own type ("Purchase #PUR-00003");
      // vouchers now do the same with their real type name ("Expense #",
      // "Advance Payment #", ...) instead.
      const docLabel = isSecurityDeposit
        ? (v.receipt_no ? `${t('tx.receiptHashPrefix')} ${v.receipt_no}` : t('tx.receiptFallback'))
        : (v.voucher_no ? `${label} # ${v.voucher_no}` : label)
      // A multi-line expense (several "Paid To" accounts under one "Paid
      // From") never shows its individual expense-account lines here — the
      // voucher is already one row, one combined amount. What identifies it
      // now is the accounts actually involved: which account it came from,
      // and the first of the accounts it went to.
      const hasLines = voucherIdsWithLines.has(v.id)
      const fromName = v.from_account_id ? accountNameById[v.from_account_id] : undefined
      const firstToName = accountNameById[firstLineAccountIdByVoucher[v.id]]
      const toAccountName = v.to_account_id ? accountNameById[v.to_account_id] : undefined
      const multiLineLabel = hasLines && fromName && firstToName ? `${fromName} → ${firstToName}` : null
      // Row display: the paid-to account leads, the paid-from account sits
      // under it — separate lines instead of one combined "A → B" string, so
      // a long account name on either side never has to share a line with
      // the other. Falls back to the free-text party name, then the type
      // label itself, for older/atypical vouchers with no account on either side.
      const voucherToName = (hasLines ? firstToName : toAccountName) ?? v.party_name ?? label
      const voucherFromName = fromName
      result.push({
        id: `voucher-${v.id}`, kind: 'voucher', voucherType: v.voucher_type, isRecurring: !!v.recurring_schedule_id,
        borderColor: isSecurityDeposit ? 'border-cyan-500' : 'border-slate-400',
        typeLabel: label, partyName: multiLineLabel ?? (v.party_name || label), docLabel,
        date: v.voucher_date, description: v.particular, amount: v.amount_pkr,
        badge: null, note: null, voucherId: v.id, receiptNo: v.receipt_no, autoPosted: autoPostedIds.has(v.id), fullyApproved: fullyApprovedIds.has(v.id), createdAt: v.created_at,
        hasLineItems: hasLines, voucherToName, voucherFromName, voucherNo: v.voucher_no,
        searchBlob: `${v.party_name ?? ''} ${label} ${fromName ?? ''} ${firstToName ?? ''} ${toAccountName ?? ''} ${v.voucher_no ?? ''} ${v.receipt_no ?? ''} ${v.particular ?? ''}`.toLowerCase(),
      })
    }

    for (const d of donationsRes.data ?? []) {
      result.push({
        id: `donation-${d.id}`, kind: 'donation', borderColor: 'border-violet-500', isRecurring: !!d.recurring_schedule_id,
        typeLabel: d.payment_method ? d.payment_method.charAt(0).toUpperCase() + d.payment_method.slice(1) : null,
        // Real name for staff; anonymity is enforced publicly by donors_public.
        partyName: d.is_anonymous ? `${d.name} ${t('tx.anonymousPubliclySuffix')}` : d.name,
        // A confirmed donation gets a voucher number from confirm_donation() /
        // assign_donor_numbers(); showing it here is what makes the entry
        // traceable back to the paper receipt the donor was handed.
        docLabel: d.voucher_no ? `${t('tx.receiptHashPrefix')} ${d.voucher_no}` : t('tx.donationFallback'),
        date: d.date, description: d.notes || t('tx.donationReceived'),
        amount: d.amount_pkr, note: null, createdAt: d.created_at,
        badge: (() => { const b = donationBadge(d); return { textKey: b.key, tone: b.tone } })(),
        donationId: d.id, donationVoucherNo: d.voucher_no, donationVerified: d.is_verified, receiptNo: d.voucher_no,
        searchBlob: `${d.name} ${d.payment_method ?? ''} ${d.notes ?? ''} ${d.voucher_no ?? ''}`.toLowerCase(),
      })
    }

    const purchasesList = purchasesRes.data ?? []
    let purchaseTotalsById: Record<string, number> = {}
    let purchaseItemCountById: Record<string, number> = {}
    if (purchasesList.length > 0) {
      const { data: purchaseLineRows } = await supabase.from('inventory_transactions')
        .select('purchase_id, quantity, unit_cost_at_time').in('purchase_id', purchasesList.map((p) => p.id))
      for (const r of purchaseLineRows ?? []) {
        const pid = r.purchase_id as string
        purchaseTotalsById[pid] = (purchaseTotalsById[pid] ?? 0) + r.quantity * (r.unit_cost_at_time ?? 0)
        purchaseItemCountById[pid] = (purchaseItemCountById[pid] ?? 0) + 1
      }
    }

    for (const p of purchasesList) {
      const itemCount = purchaseItemCountById[p.id] ?? 0
      result.push({
        id: `purchase-${p.id}`, kind: 'purchase', borderColor: 'border-amber-500',
        typeLabel: p.method.charAt(0).toUpperCase() + p.method.slice(1),
        partyName: p.vendor || t('tx.purchaseFallback'), docLabel: p.purchase_number ? `${t('tx.purchaseHash')} ${p.purchase_number}` : t('tx.purchaseBillFallback'),
        date: p.purchase_date, description: itemCount > 0 ? `${itemCount} ${t('tx.itemsPurchasedSuffix')}${p.note ? ' — ' + p.note : ''}` : (p.note || t('tx.inventoryPurchase')),
        amount: purchaseTotalsById[p.id] ?? 0, badge: null, note: p.note, purchaseId: p.id, purchaseNumber: p.purchase_number,
        autoPosted: autoPostedIds.has(p.id), fullyApproved: fullyApprovedIds.has(p.id), createdAt: p.created_at,
        searchBlob: `${p.vendor ?? ''} ${p.method} ${p.note ?? ''}`.toLowerCase(),
      })
    }

    result.sort((a, b) => (a.date !== b.date ? (a.date < b.date ? 1 : -1) : (a.createdAt < b.createdAt ? 1 : a.createdAt > b.createdAt ? -1 : 0)))
    setRows(result)
    setLoading(false)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [system, from, to, supabase, t, isUrdu])

  useEffect(() => { load() }, [load])

  const filteredRows = useMemo(() => {
    const q = search.trim().toLowerCase()
    return rows.filter((r) => {
      if (statusFilter !== 'all') {
        if (r.kind !== 'bill' || !r.badge) return false
        const tone = r.badge.tone
        if (statusFilter === 'paid' && tone !== 'green') return false
        if (statusFilter === 'partial' && tone !== 'amber') return false
        if (statusFilter === 'pending' && tone !== 'gray') return false
        if (statusFilter === 'overdue' && tone !== 'red') return false
      }
      if (kindFilter !== 'all') {
        if (kindFilter.startsWith('voucher:')) {
          const vt = kindFilter.slice('voucher:'.length)
          // An advance settlement's real economic effect is an expense (see
          // migration 090) — it should surface under the Expense filter too.
          const matchesType = r.voucherType === vt || (vt === 'expense' && r.voucherType === 'advance_settlement')
          if (r.kind !== 'voucher' || !matchesType) return false
        } else if (r.kind !== kindFilter) {
          return false
        }
      }
      if (autoPostedOnly && !r.autoPosted) return false
      if (q && !r.searchBlob.includes(q)) return false
      return true
    })
    // Auto-posted (no full confirmation before the 24h deadline) sorts to the
    // top within the existing date-descending order, so they're easy to spot
    // and audit even without turning on the dedicated filter above.
    .sort((a, b) => (a.autoPosted === b.autoPosted ? 0 : a.autoPosted ? -1 : 1))
  }, [rows, statusFilter, kindFilter, autoPostedOnly, search])

  // A read-only audit view — View is the one action that belongs here regardless
  // of type; Edit/Delete stay on the Transactions (finance) page that owns them.
  const openRowReceipt = async (r: TxnRow) => {
    if (r.kind === 'payment' && r.paymentId) {
      setViewReceipt({
        kind: 'payment', receiptNo: r.receiptNo ?? r.paymentId.slice(0, 8).toUpperCase(),
        date: r.date, systemLabel: systemLabels[system], accountName: r.partyName,
        particular: r.description, amount: r.amount, balanceAfter: 0,
      })
    } else if (r.kind === 'voucher' && r.voucherId) {
      // A multi-category voucher (Kafalat's monthly payment, a water_supply
      // multi-line expense) posts through voucher_line_items -- this is the
      // third, independent place a voucher's receipt gets built (the
      // Transactions Workspace and the account statement page each had
      // their own copy of this same gap) and it never had the breakdown
      // wired in either.
      const { data: items } = await supabase.from('voucher_line_items')
        .select('description, category, amount').eq('voucher_id', r.voucherId)
      const lineItems = items && items.length > 0
        ? items.map((l) => ({
            description: l.description || (l.category ? l.category.replace(/_/g, ' ').replace(/\b\w/g, (c: string) => c.toUpperCase()) : 'Item'),
            quantity: 1, unitPrice: Number(l.amount),
          }))
        : undefined
      setViewReceipt({
        kind: voucherReceiptKind[r.voucherType ?? ''] ?? 'manual',
        receiptNo: r.receiptNo ?? r.voucherNo ?? r.voucherId.slice(0, 8).toUpperCase(),
        date: r.date, systemLabel: systemLabels[system], accountName: r.voucherToName ?? r.partyName,
        particular: r.description, amount: r.amount, balanceAfter: 0,
        paidFromName: r.voucherFromName,
        lineItems,
      })
    } else if (r.kind === 'purchase' && r.purchaseId) {
      setViewReceipt({
        kind: 'purchase_payment', receiptNo: r.purchaseNumber ?? r.purchaseId.slice(0, 8).toUpperCase(),
        date: r.date, systemLabel: systemLabels[system], accountName: r.partyName,
        particular: r.note || r.description, amount: r.amount, balanceAfter: 0,
      })
    } else if (r.kind === 'donation' && r.donationId) {
      const totals = await donorReceiptTotals(r.donationId)
      setViewReceipt({
        kind: 'donation', receiptNo: r.donationVoucherNo ?? '—',
        date: r.date, systemLabel: systemLabels[system], accountName: r.partyName,
        particular: r.description, amount: r.amount,
        balanceAfter: totals.totalContributed, announcedRemaining: totals.announcedRemaining,
        projectName: totals.projectName,
      isConfirmed: totals.isConfirmed,
      })
    }
  }

  return (
    <div dir={isUrdu ? 'rtl' : 'ltr'}>
      <div className="flex items-center justify-between mb-6 gap-4 flex-wrap">
        <h1 className="font-heading text-[28px] font-bold leading-[36px] text-dp-primary">{t('tx.title')}</h1>
        {!access.loading && (access.canWaterSupply || access.canDonorsProjects) && (
          <div className="flex items-center gap-1 bg-dp-surface-container-low rounded-lg p-1">
            {access.canWaterSupply && (
              <button onClick={() => setSystem('water_supply')} className={`px-3 py-1.5 rounded-md text-[13px] font-sans font-semibold cursor-pointer transition-all ${system === 'water_supply' ? 'bg-dp-secondary text-white' : 'text-dp-on-surface-variant'}`}>{t('a.waterSupply')}</button>
            )}
            {access.canDonorsProjects && (
              <button onClick={() => setSystem('donors_projects')} className={`px-3 py-1.5 rounded-md text-[13px] font-sans font-semibold cursor-pointer transition-all ${system === 'donors_projects' ? 'bg-dp-secondary text-white' : 'text-dp-on-surface-variant'}`}>{t('a.donorsProjects')}</button>
            )}
          </div>
        )}
      </div>

      {/* Search bar + filter trigger, one row — replaces the old always-open
          bar of labeled fields (six-plus controls wrapping badly under
          ~640px, three of them native <select>s that render as the OS's
          own dark picker regardless of this page's white theme). The
          button carries the active date range as its own label, so that's
          visible without opening the sheet; a dot marks any other filter
          left non-default. */}
      <div className="flex items-center gap-2 mb-2">
        <div className="relative flex-1 min-w-0">
          <Search size={15} className="absolute start-3 top-1/2 -translate-y-1/2 text-dp-on-surface-variant pointer-events-none" />
          <input
            value={search} onChange={(e) => setSearch(e.target.value)}
            placeholder={t('tx.searchPlaceholder')}
            className="input-field !ps-9 text-[14px]"
          />
        </div>
        <button
          onClick={() => setShowFilterSheet(true)}
          className="relative shrink-0 flex items-center gap-1.5 px-3 py-2.5 bg-white border border-dp-outline-variant rounded-lg font-sans text-[13px] font-semibold text-dp-on-surface hover:border-dp-primary/30 hover:text-dp-primary transition-all cursor-pointer"
        >
          <SlidersHorizontal size={15} />
          <span dir="ltr" className="whitespace-nowrap">{formatRangeLabel(from, to)}</span>
          {(statusFilter !== 'all' || kindFilter !== 'all' || autoPostedOnly) && (
            <span className="absolute -top-1 -end-1 w-2.5 h-2.5 rounded-full bg-dp-error" aria-hidden />
          )}
        </button>
      </div>
      <p className="font-sans text-[12px] text-dp-on-surface-variant mb-4">{t('tx.showingCountNote').replace('{shown}', String(filteredRows.length)).replace('{total}', String(rows.length))}</p>

      <FilterSheet
        open={showFilterSheet}
        title={t('fr.filterTransactions')}
        onClose={() => setShowFilterSheet(false)}
        onApply={() => setShowFilterSheet(false)}
        applyLabel={t('fr.apply')}
      >
        <FilterSheetSection label={t('fr.dateRange')}>
          <DateRangePillGroup
            options={PRESET_ORDER.map((k) => ({ key: k, label: t(presetLabelKey(k)) }))}
            active={activePreset}
            onSelect={(k) => applyPreset(k as DateRangePreset)}
          />
        </FilterSheetSection>
        <div className="grid grid-cols-2 gap-3">
          <div>
            <label className="block font-sans text-[12px] font-semibold text-dp-on-surface-variant mb-1.5">{t('fr.startDate')}</label>
            <input type="date" value={from} onChange={(e) => setFrom(e.target.value)} className="input-field text-[14px]" />
          </div>
          <div>
            <label className="block font-sans text-[12px] font-semibold text-dp-on-surface-variant mb-1.5">{t('fr.endDate')}</label>
            <input type="date" value={to} onChange={(e) => setTo(e.target.value)} className="input-field text-[14px]" />
          </div>
        </div>
        <SearchableField
          label={t('fr.transactionType')}
          value={kindFilter}
          onChange={setKindFilter}
          pickerTitle={t('fr.transactionType')}
          items={[
            { id: 'all', label: t('tx.allTypes') },
            { id: 'bill', label: t('tx.bills') },
            { id: 'payment', label: t('tx.paymentsReceipts') },
            ...(system === 'donors_projects' ? [{ id: 'donation', label: t('tx.donations') }] : []),
            ...(system === 'water_supply' ? [{ id: 'purchase', label: t('tx.purchases') }] : []),
            { id: 'voucher:expense', label: t('tx.expenseVouchers') },
            { id: 'voucher:income', label: t('tx.incomeVouchers') },
            { id: 'voucher:contra', label: t('tx.bankTransfers') },
            { id: 'voucher:withdrawal', label: t('tx.cashWithdrawals') },
            { id: 'voucher:deposit', label: t('tx.cashDeposits') },
            { id: 'voucher:advance', label: t('tx.advancePayments') },
            { id: 'voucher:security_deposit', label: t('tx.securityDeposits') },
            { id: 'voucher:security_deposit_refund', label: t('tx.depositRefunds') },
          ]}
        />
        <SearchableField
          label={t('w.status')}
          value={statusFilter}
          onChange={(id) => setStatusFilter(id as typeof statusFilter)}
          pickerTitle={t('w.status')}
          items={[
            { id: 'all', label: t('tx.allStatuses') },
            { id: 'paid', label: t('w.paid') },
            { id: 'partial', label: t('tx.partial') },
            { id: 'pending', label: t('tx.pending') },
            { id: 'overdue', label: t('tx.overdue') },
          ]}
        />
        <label className="flex items-center gap-2.5 cursor-pointer" title={t('tx.autoPostedTooltip')}>
          <input type="checkbox" checked={autoPostedOnly} onChange={(e) => setAutoPostedOnly(e.target.checked)} className="w-4 h-4 accent-dp-secondary" />
          <span className="font-sans text-[13.5px] text-dp-on-surface">{t('tx.autoPostedOnly')}</span>
        </label>
      </FilterSheet>

      <div className="bg-white rounded-lg border border-dp-outline-variant overflow-hidden">
        {loading && <p className="px-4 py-8 text-center text-dp-on-surface-variant font-sans text-[13.5px]">{t('action.loading')}</p>}
        {!loading && filteredRows.length === 0 && <p className="px-4 py-8 text-center text-dp-on-surface-variant font-sans text-[13.5px]">{t('tx.noMatch')}</p>}
        <div className="divide-y divide-dp-outline-variant">
          {!loading && filteredRows.map((r) => (
            <div key={r.id} className={`flex border-s-[3px] ${r.borderColor}`}>
              <div className="flex-1 min-w-0 p-3.5">
                {r.kind === 'voucher' ? (
                  // Voucher rows lead with the two accounts actually involved
                  // (paid-to on top, paid-from underneath) instead of a
                  // free-text party name — and the type/number/amount/status
                  // stack sits on its own side, so a long account name can
                  // never crowd the status pills or vice versa.
                  <div className="flex justify-between items-start gap-3">
                    <div className="min-w-0 flex-1">
                      <p className="font-sans text-[14px] font-bold text-dp-on-surface truncate">{r.voucherToName}</p>
                      {r.voucherFromName && (
                        <p className="font-sans text-[12px] text-dp-on-surface-variant truncate">{r.voucherFromName}</p>
                      )}
                      <p className="font-sans text-[13px] text-dp-on-surface-variant mt-1">{r.description}</p>
                    </div>
                    <div className="text-end shrink-0">
                      <p className="font-sans text-[13px] font-bold text-dp-on-surface whitespace-nowrap">{r.docLabel}</p>
                      <p className="font-sans text-[12px] text-dp-on-surface-variant whitespace-nowrap">{new Date(r.date).toLocaleDateString('en-GB')}</p>
                      {r.amount > 0 && <p className="font-sans text-[15px] font-bold text-dp-on-surface whitespace-nowrap mt-1">Rs {fmtAmount(r.amount)}</p>}
                      <div className="flex flex-wrap justify-end gap-1 mt-1">
                        {r.isRecurring && (
                          <span className="inline-block px-1.5 py-0.5 rounded font-sans text-[10px] font-bold uppercase tracking-wide bg-indigo-100 text-indigo-700" title={t('tx.recurringTooltip')}>
                            {t('a.recurring')}
                          </span>
                        )}
                        {r.autoPosted && (
                          <span className="inline-block px-1.5 py-0.5 rounded font-sans text-[10px] font-bold uppercase tracking-wide bg-amber-100 text-amber-800" title={t('tx.autoPostedRowTooltip')}>
                            {t('a.autoPosted')}
                          </span>
                        )}
                        {r.fullyApproved && (
                          <span className="inline-block px-1.5 py-0.5 rounded font-sans text-[10px] font-bold uppercase tracking-wide bg-emerald-100 text-emerald-800" title={t('tx.fullyApprovedTooltip')}>
                            {t('f.approved')}
                          </span>
                        )}
                      </div>
                    </div>
                  </div>
                ) : (
                  <>
                    <div className="flex justify-between items-start gap-3">
                      <div className="min-w-0">
                        {r.typeLabel && <p className="font-sans text-[11.5px] text-dp-on-surface-variant leading-tight">{r.typeLabel}</p>}
                        <p className="font-sans text-[14px] font-bold text-dp-on-surface truncate">{r.partyName}</p>
                        {r.isRecurring && (
                          <span className="inline-block mt-0.5 me-1 px-1.5 py-0.5 rounded font-sans text-[10px] font-bold uppercase tracking-wide bg-indigo-100 text-indigo-700" title={t('tx.recurringTooltip')}>
                            {t('a.recurring')}
                          </span>
                        )}
                        {r.autoPosted && (
                          <span className="inline-block mt-0.5 px-1.5 py-0.5 rounded font-sans text-[10px] font-bold uppercase tracking-wide bg-amber-100 text-amber-800" title={t('tx.autoPostedRowTooltip')}>
                            {t('a.autoPosted')}
                          </span>
                        )}
                        {r.fullyApproved && (
                          <span className="inline-block mt-0.5 px-1.5 py-0.5 rounded font-sans text-[10px] font-bold uppercase tracking-wide bg-emerald-100 text-emerald-800" title={t('tx.fullyApprovedTooltip')}>
                            {t('f.approved')}
                          </span>
                        )}
                      </div>
                      <div className="text-end shrink-0">
                        <p className="font-sans text-[13px] font-bold text-dp-on-surface whitespace-nowrap">{r.docLabel}</p>
                        <p className="font-sans text-[12px] text-dp-on-surface-variant whitespace-nowrap">{new Date(r.date).toLocaleDateString('en-GB')}</p>
                      </div>
                    </div>
                    <div className="flex justify-between items-end gap-3 mt-1.5">
                      <p className="font-sans text-[13px] text-dp-on-surface-variant truncate">{r.description}</p>
                      <div className="text-end shrink-0">
                        {r.amount > 0 && <p className="font-sans text-[15px] font-bold text-dp-on-surface whitespace-nowrap">Rs {fmtAmount(r.amount)}</p>}
                        {r.badge && (
                          <span className={`inline-block mt-1 px-2 py-0.5 rounded font-sans text-[10.5px] font-bold tracking-wide ${billBadgeClass[r.badge.tone]}`}>{r.badge.textKey ? t(r.badge.textKey) : r.badge.text}</span>
                        )}
                      </div>
                    </div>
                  </>
                )}
                {/* Edit/Delete hand the record back to the screen that owns
                    its form and its rules — a bill's Delete still goes
                    through attemptDeleteBill's own payments-must-go-first
                    check, a closed month still shows nothing here rather
                    than a control that would fail — instead of keeping a
                    second copy of any of that logic on this list. */}
                {(r.billId || r.kind === 'payment' || r.kind === 'voucher' || r.kind === 'purchase' || r.kind === 'donation') && (
                  <div className="flex justify-end items-center gap-1 mt-2 pt-2 border-t border-dp-outline-variant/60">
                    {r.billId && (
                      <Link href={`/admin/invoice/bill/${r.billId}`} title={t('tx.viewInvoiceTitle')} className="p-1.5 text-dp-on-surface-variant hover:text-dp-secondary cursor-pointer"><FileText size={15} /></Link>
                    )}
                    {(r.kind === 'payment' || r.kind === 'voucher' || r.kind === 'purchase' || r.kind === 'donation') && (
                      <button onClick={() => openRowReceipt(r)} title={t('tx.viewReceiptTitle')} className="p-1.5 text-dp-on-surface-variant hover:text-dp-secondary cursor-pointer"><Eye size={15} /></button>
                    )}
                    {!dateIsLocked(r.date, lockRule) && (
                      <>
                        {r.kind === 'bill' && r.billId && (
                          <>
                            <Link href={`/admin/finance/${system}?action=generate_bill&bill=${r.billId}`} title={t('tx.editBillTitle')} className="p-1.5 text-dp-on-surface-variant hover:text-dp-primary cursor-pointer"><Pencil size={15} /></Link>
                            <Link href={`/admin/finance/${system}?delete_bill=${r.billId}`} title={t('tx.deleteBillTitle')} className="p-1.5 text-dp-on-surface-variant hover:text-dp-error cursor-pointer"><Trash2 size={15} /></Link>
                          </>
                        )}
                        {r.kind === 'payment' && r.paymentId && (
                          <>
                            <Link href={`/admin/finance/${system}?edit_payment=${r.paymentId}`} title={t('tx.editPaymentTitle')} className="p-1.5 text-dp-on-surface-variant hover:text-dp-primary cursor-pointer"><Pencil size={15} /></Link>
                            <Link href={`/admin/finance/${system}?delete_payment=${r.paymentId}`} title={t('tx.deletePaymentTitle')} className="p-1.5 text-dp-on-surface-variant hover:text-dp-error cursor-pointer"><Trash2 size={15} /></Link>
                          </>
                        )}
                        {r.kind === 'voucher' && r.voucherId && (
                          <>
                            {r.hasLineItems ? (
                              <span title={t('tx.hasLineItemsTooltip')} className="p-1.5 text-dp-on-surface-variant/40 cursor-not-allowed"><Pencil size={15} /></span>
                            ) : (
                              <Link href={`/admin/finance/${system}?edit_voucher=${r.voucherId}`} title={t('tx.editVoucherTitle')} className="p-1.5 text-dp-on-surface-variant hover:text-dp-primary cursor-pointer"><Pencil size={15} /></Link>
                            )}
                            <Link href={`/admin/finance/${system}?delete_voucher=${r.voucherId}`} title={t('tx.deleteVoucherTitle')} className="p-1.5 text-dp-on-surface-variant hover:text-dp-error cursor-pointer"><Trash2 size={15} /></Link>
                          </>
                        )}
                        {r.kind === 'donation' && r.donationId && (
                          <Link href={`/admin/donors?edit=${r.donationId}`} title={r.donationVerified ? t('tx.editDonationTitle') : t('tx.reviewConfirmTitle')} className="p-1.5 text-dp-on-surface-variant hover:text-dp-primary cursor-pointer"><Pencil size={15} /></Link>
                        )}
                      </>
                    )}
                  </div>
                )}
              </div>
            </div>
          ))}
        </div>
      </div>
      {viewReceipt && <ReceiptModal data={viewReceipt} system={system} onClose={() => setViewReceipt(null)} />}

    </div>
  )
}
