'use client'

import { useEffect, useState, useCallback, useMemo } from 'react'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/client'
import { Search, FileText, Eye, Pencil, Trash2 } from 'lucide-react'
import { toast } from 'sonner'
import { ConfirmDialog } from '@/components/admin/ConfirmDialog'
import { friendlyError } from '@/lib/errors'
import { billBadge, billBadgeClass, type BillBadgeTone } from '@/lib/billStatus'
import { useSystemAccess } from '@/hooks/useSystemAccess'
import { voucherTypeLabels, voucherReceiptKind } from '@/lib/ledgerLabels'
import { ReceiptModal } from '@/components/admin/ReceiptModal'
import type { ReceiptData } from '@/components/admin/ReceiptDocument'
import { donorReceiptTotals } from '@/lib/donorReceiptTotals'
import { useLocale } from '@/lib/i18n/LocaleProvider'

type SystemTab = 'water_supply' | 'donors_projects'

interface TxnRow {
  id: string
  kind: 'bill' | 'payment' | 'voucher' | 'donation' | 'purchase'
  voucherType?: string
  borderColor: string
  typeLabel: string | null
  partyName: string
  docLabel: string
  date: string
  description: string
  amount: number
  badge: { text: string; tone: BillBadgeTone } | null
  note: string | null
  searchBlob: string
  billId?: string
  paymentId?: string
  voucherId?: string
  purchaseId?: string
  purchaseNumber?: string | null
  donationId?: string
  donationVoucherNo?: string | null
  donationVerified?: boolean
  // Generated by a recurring schedule rather than entered by hand.
  isRecurring?: boolean
  receiptNo?: string | null
  autoPosted?: boolean
  fullyApproved?: boolean
  createdAt: string
}

const systemLabels: Record<SystemTab, string> = { water_supply: 'Water Supply System', donors_projects: 'Donors & Projects System' }

function fmtAmount(n: number) {
  return Number(n).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })
}
const today = () => new Date().toISOString().slice(0, 10)
const monthStart = () => { const d = new Date(); d.setDate(1); return d.toISOString().slice(0, 10) }
const yearStart = (y: number) => `${y}-01-01`
const yearEnd = (y: number) => `${y}-12-31`

export default function AllTransactionsPage() {
  const { t } = useLocale()
  const access = useSystemAccess()
  const [system, setSystem] = useState<SystemTab>('water_supply')
  const [systemOverride] = useState<SystemTab | null>(() => {
    if (typeof window === 'undefined') return null
    const p = new URLSearchParams(window.location.search).get('system')
    return p === 'water_supply' || p === 'donors_projects' ? p : null
  })
  useEffect(() => {
    if (access.loading) return
    if (systemOverride === 'water_supply' && access.canWaterSupply) { setSystem('water_supply'); return }
    if (systemOverride === 'donors_projects' && access.canDonorsProjects) { setSystem('donors_projects'); return }
    setSystem(access.defaultSystem)
  }, [access.loading, access.defaultSystem, access.canWaterSupply, access.canDonorsProjects, systemOverride])
  const [from, setFrom] = useState(monthStart())
  const [to, setTo] = useState(today())
  const [statusFilter, setStatusFilter] = useState<'all' | 'paid' | 'partial' | 'pending' | 'overdue'>('all')
  const [kindFilter, setKindFilter] = useState('all')
  const [autoPostedOnly, setAutoPostedOnly] = useState(false)
  const [search, setSearch] = useState('')
  const [rows, setRows] = useState<TxnRow[]>([])
  const [viewReceipt, setViewReceipt] = useState<ReceiptData | null>(null)
  const [confirmDelete, setConfirmDelete] = useState<{ kind: 'payment' | 'voucher' | 'donation' | 'bill'; id: string } | null>(null)
  const [billDeleteBlock, setBillDeleteBlock] = useState<string[] | null>(null)
  const [loading, setLoading] = useState(true)
  const supabase = createClient()

  const applyYear = (y: string) => {
    if (!y) return
    const yr = +y
    const isCurrent = yr === new Date().getFullYear()
    setFrom(yearStart(yr))
    setTo(isCurrent ? today() : yearEnd(yr))
  }

  const setCurrentMonth = () => { setFrom(monthStart()); setTo(today()) }

  const load = useCallback(async () => {
    setLoading(true)
    const [consumersRes, billsRes, paymentsRes, vouchersRes, donationsRes, purchasesRes, autoPostedRes] = await Promise.all([
      system === 'water_supply'
        ? supabase.from('consumers').select('consumer_id, name, mobile')
        : Promise.resolve({ data: [] as { consumer_id: string; name: string; mobile: string }[] }),
      system === 'water_supply'
        ? supabase.from('bills').select('id, bill_number, consumer_id, month, year, amount_pkr, discount_amount, paid_amount, due_date, description, created_at, security_deposit_amount, security_deposit_voucher_id, recurring_schedule_id')
            .gte('created_at', from).lte('created_at', `${to}T23:59:59`)
        : Promise.resolve({ data: [] as { id: string; bill_number: string | null; consumer_id: string; month: number; year: number; amount_pkr: number; discount_amount: number | null; paid_amount: number | null; due_date: string | null; description: string | null; created_at: string; security_deposit_amount: number | null; security_deposit_voucher_id: string | null; recurring_schedule_id: string | null }[] }),
      system === 'water_supply'
        ? supabase.from('payments').select('id, bill_id, consumer_id, amount_pkr, method, paid_date, receipt_no, note, created_at').gte('paid_date', from).lte('paid_date', to)
        : Promise.resolve({ data: [] as { id: string; bill_id: string; consumer_id: string; amount_pkr: number; method: string | null; paid_date: string; receipt_no: string | null; note: string | null; created_at: string }[] }),
      supabase.from('vouchers').select('id, voucher_type, voucher_no, receipt_no, voucher_date, particular, amount_pkr, party_name, bill_id, created_at, recurring_schedule_id')
        .eq('system', system).in('status', ['posted', 'approved']).gte('voucher_date', from).lte('voucher_date', to),
      system === 'donors_projects'
        ? supabase.from('donors').select('id, name, amount_pkr, date, payment_method, notes, is_anonymous, created_at, voucher_no, is_verified, payment_status, recurring_schedule_id').gte('date', from).lte('date', to)
        : Promise.resolve({ data: [] as { id: string; name: string; amount_pkr: number; date: string; payment_method: string | null; notes: string | null; is_anonymous: boolean; created_at: string; voucher_no: string | null; is_verified: boolean; payment_status: string | null; recurring_schedule_id: string | null }[] }),
      system === 'water_supply'
        ? supabase.from('purchases').select('id, vendor, purchase_date, method, note, purchase_number, created_at').eq('system', system).eq('status', 'posted').gte('purchase_date', from).lte('purchase_date', to)
        : Promise.resolve({ data: [] as { id: string; vendor: string | null; purchase_date: string; method: string; note: string | null; purchase_number: string | null; created_at: string }[] }),
      // Auto-posted = the transaction went live after the 24-hour deadline
      // without every configured approver confirming (migration 060) — flagged
      // here so it can be surfaced/filtered separately from a normally-approved one.
      supabase.from('approval_requests').select('reference_id, auto_posted').eq('system', system).eq('status', 'posted'),
    ])
    const autoPostedIds = new Set((autoPostedRes.data ?? []).filter((r) => r.auto_posted).map((r) => r.reference_id))
    const fullyApprovedIds = new Set((autoPostedRes.data ?? []).filter((r) => !r.auto_posted).map((r) => r.reference_id))

    const consumersById = Object.fromEntries((consumersRes.data ?? []).map((c) => [c.consumer_id, c]))
    const billNumberById = Object.fromEntries((billsRes.data ?? []).map((b) => [b.id, b.bill_number]))
    // A security deposit collected with a bill posts as its own voucher for
    // real double-entry correctness, but it's the same cash-collection event —
    // fold its receipt info into the bill's row instead of showing it as an
    // unrelated third transaction.
    const depositReceiptByVoucherId = Object.fromEntries(
      (vouchersRes.data ?? []).filter((v) => v.voucher_type === 'security_deposit').map((v) => [v.id, v.receipt_no])
    )
    const result: TxnRow[] = []

    for (const b of billsRes.data ?? []) {
      const net = Math.max(b.amount_pkr - (b.discount_amount ?? 0), 0)
      const consumer = consumersById[b.consumer_id]
      let description = b.description || `Water Bill — ${new Date(b.year, b.month - 1, 1).toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}`
      if (b.security_deposit_amount && b.security_deposit_amount > 0) {
        const receiptNo = b.security_deposit_voucher_id ? depositReceiptByVoucherId[b.security_deposit_voucher_id] : null
        description += ` · + Security Deposit Rs ${fmtAmount(b.security_deposit_amount)}${receiptNo ? ` (Receipt # ${receiptNo})` : ''}`
      }
      result.push({
        id: `bill-${b.id}`, kind: 'bill', borderColor: 'border-emerald-500', isRecurring: !!b.recurring_schedule_id,
        typeLabel: null, partyName: consumer?.name ?? b.consumer_id,
        docLabel: b.bill_number ? `Bill # ${b.bill_number}` : 'Bill',
        date: b.due_date ?? new Date(b.year, b.month - 1, 1).toISOString().slice(0, 10),
        description, amount: net, badge: billBadge(b), note: null, billId: b.id, createdAt: b.created_at,
        searchBlob: `${consumer?.name ?? ''} ${b.consumer_id} ${consumer?.mobile ?? ''} ${b.bill_number ?? ''} ${b.description ?? ''}`.toLowerCase(),
      })
    }

    for (const p of paymentsRes.data ?? []) {
      const billNo = billNumberById[p.bill_id]
      const consumer = consumersById[p.consumer_id]
      result.push({
        id: `payment-${p.id}`, kind: 'payment', borderColor: 'border-cyan-500',
        typeLabel: p.method ? p.method.charAt(0).toUpperCase() + p.method.slice(1) : 'Cash',
        partyName: consumer?.name ?? p.consumer_id,
        docLabel: p.receipt_no ? `Receipt # ${p.receipt_no}` : 'Receipt',
        date: p.paid_date, description: billNo ? `Against Bill ${billNo}` : (p.note || 'Payment received'),
        amount: p.amount_pkr, badge: null, note: p.note, billId: p.bill_id, paymentId: p.id, receiptNo: p.receipt_no, createdAt: p.created_at,
        searchBlob: `${consumer?.name ?? ''} ${p.consumer_id} ${consumer?.mobile ?? ''} ${p.receipt_no ?? ''} ${p.method ?? ''} ${p.note ?? ''}`.toLowerCase(),
      })
    }

    for (const v of vouchersRes.data ?? []) {
      // Bill-linked security deposits are now folded into their bill's row above.
      if (v.voucher_type === 'security_deposit' && v.bill_id) continue
      const isSecurityDeposit = v.voucher_type === 'security_deposit'
      const docLabel = isSecurityDeposit
        ? (v.receipt_no ? `Receipt # ${v.receipt_no}` : 'Receipt')
        : (v.voucher_no ? `Voucher # ${v.voucher_no}` : 'Voucher')
      const label = voucherTypeLabels[v.voucher_type] ?? v.voucher_type.replace(/_/g, ' ')
      result.push({
        id: `voucher-${v.id}`, kind: 'voucher', voucherType: v.voucher_type, isRecurring: !!v.recurring_schedule_id,
        borderColor: isSecurityDeposit ? 'border-cyan-500' : 'border-slate-400',
        typeLabel: label, partyName: v.party_name || label, docLabel,
        date: v.voucher_date, description: v.particular, amount: v.amount_pkr,
        badge: null, note: null, voucherId: v.id, receiptNo: v.receipt_no, autoPosted: autoPostedIds.has(v.id), fullyApproved: fullyApprovedIds.has(v.id), createdAt: v.created_at,
        searchBlob: `${v.party_name ?? ''} ${label} ${v.voucher_no ?? ''} ${v.receipt_no ?? ''} ${v.particular ?? ''}`.toLowerCase(),
      })
    }

    for (const d of donationsRes.data ?? []) {
      result.push({
        id: `donation-${d.id}`, kind: 'donation', borderColor: 'border-violet-500', isRecurring: !!d.recurring_schedule_id,
        typeLabel: d.payment_method ? d.payment_method.charAt(0).toUpperCase() + d.payment_method.slice(1) : null,
        // Real name for staff; anonymity is enforced publicly by donors_public.
        partyName: d.is_anonymous ? `${d.name} (anonymous publicly)` : d.name,
        docLabel: 'Donation', date: d.date, description: d.notes || 'Donation received',
        amount: d.amount_pkr, note: null, createdAt: d.created_at,
        badge: d.is_verified
          ? { text: 'Received', tone: 'green' as BillBadgeTone }
          : d.payment_status === 'pledged'
            ? { text: 'Announced', tone: 'amber' as BillBadgeTone }
            : { text: 'Awaiting confirmation', tone: 'gray' as BillBadgeTone },
        donationId: d.id, donationVoucherNo: d.voucher_no, donationVerified: d.is_verified,
        searchBlob: `${d.name} ${d.payment_method ?? ''} ${d.notes ?? ''}`.toLowerCase(),
      })
    }

    const purchasesList = purchasesRes.data ?? []
    let purchaseTotalsById: Record<string, number> = {}
    let purchaseItemCountById: Record<string, number> = {}
    if (purchasesList.length > 0) {
      const { data: purchaseLineRows } = await supabase.from('inventory_transactions')
        .select('purchase_id, quantity, unit_cost_at_time').in('purchase_id', purchasesList.map((p) => p.id))
      for (const r of purchaseLineRows ?? []) {
        const pid = r.purchase_id as string
        purchaseTotalsById[pid] = (purchaseTotalsById[pid] ?? 0) + r.quantity * (r.unit_cost_at_time ?? 0)
        purchaseItemCountById[pid] = (purchaseItemCountById[pid] ?? 0) + 1
      }
    }

    for (const p of purchasesList) {
      const itemCount = purchaseItemCountById[p.id] ?? 0
      result.push({
        id: `purchase-${p.id}`, kind: 'purchase', borderColor: 'border-amber-500',
        typeLabel: p.method.charAt(0).toUpperCase() + p.method.slice(1),
        partyName: p.vendor || 'Purchase', docLabel: p.purchase_number ? `Purchase # ${p.purchase_number}` : 'Purchase Bill',
        date: p.purchase_date, description: itemCount > 0 ? `${itemCount} item${itemCount > 1 ? 's' : ''} purchased${p.note ? ' — ' + p.note : ''}` : (p.note || 'Inventory purchase'),
        amount: purchaseTotalsById[p.id] ?? 0, badge: null, note: p.note, purchaseId: p.id, purchaseNumber: p.purchase_number,
        autoPosted: autoPostedIds.has(p.id), fullyApproved: fullyApprovedIds.has(p.id), createdAt: p.created_at,
        searchBlob: `${p.vendor ?? ''} ${p.method} ${p.note ?? ''}`.toLowerCase(),
      })
    }

    result.sort((a, b) => (a.date !== b.date ? (a.date < b.date ? 1 : -1) : (a.createdAt < b.createdAt ? 1 : a.createdAt > b.createdAt ? -1 : 0)))
    setRows(result)
    setLoading(false)
  }, [system, from, to, supabase])

  useEffect(() => { load() }, [load])

  const filteredRows = useMemo(() => {
    const q = search.trim().toLowerCase()
    return rows.filter((r) => {
      if (statusFilter !== 'all') {
        if (r.kind !== 'bill' || !r.badge) return false
        const tone = r.badge.tone
        if (statusFilter === 'paid' && tone !== 'green') return false
        if (statusFilter === 'partial' && tone !== 'amber') return false
        if (statusFilter === 'pending' && tone !== 'gray') return false
        if (statusFilter === 'overdue' && tone !== 'red') return false
      }
      if (kindFilter !== 'all') {
        if (kindFilter.startsWith('voucher:')) {
          const vt = kindFilter.slice('voucher:'.length)
          // An advance settlement's real economic effect is an expense (see
          // migration 090) — it should surface under the Expense filter too.
          const matchesType = r.voucherType === vt || (vt === 'expense' && r.voucherType === 'advance_settlement')
          if (r.kind !== 'voucher' || !matchesType) return false
        } else if (r.kind !== kindFilter) {
          return false
        }
      }
      if (autoPostedOnly && !r.autoPosted) return false
      if (q && !r.searchBlob.includes(q)) return false
      return true
    })
    // Auto-posted (no full confirmation before the 24h deadline) sorts to the
    // top within the existing date-descending order, so they're easy to spot
    // and audit even without turning on the dedicated filter above.
    .sort((a, b) => (a.autoPosted === b.autoPosted ? 0 : a.autoPosted ? -1 : 1))
  }, [rows, statusFilter, kindFilter, autoPostedOnly, search])

  const years = useMemo(() => {
    const currentYear = new Date().getFullYear()
    return Array.from({ length: 6 }, (_, i) => currentYear - i)
  }, [])

  // A read-only audit view — View is the one action that belongs here regardless
  // of type; Edit/Delete stay on the Transactions (finance) page that owns them.
  const openRowReceipt = async (r: TxnRow) => {
    if (r.kind === 'payment' && r.paymentId) {
      setViewReceipt({
        kind: 'payment', receiptNo: r.receiptNo ?? r.paymentId.slice(0, 8).toUpperCase(),
        date: r.date, systemLabel: systemLabels[system], accountName: r.partyName,
        particular: r.description, amount: r.amount, balanceAfter: 0,
      })
    } else if (r.kind === 'voucher' && r.voucherId) {
      setViewReceipt({
        kind: voucherReceiptKind[r.voucherType ?? ''] ?? 'manual',
        receiptNo: r.receiptNo ?? r.docLabel.replace(/^(Voucher # |Receipt # )/, '') ?? r.voucherId.slice(0, 8).toUpperCase(),
        date: r.date, systemLabel: systemLabels[system], accountName: r.partyName,
        particular: r.description, amount: r.amount, balanceAfter: 0,
      })
    } else if (r.kind === 'purchase' && r.purchaseId) {
      setViewReceipt({
        kind: 'purchase_payment', receiptNo: r.purchaseNumber ?? r.purchaseId.slice(0, 8).toUpperCase(),
        date: r.date, systemLabel: systemLabels[system], accountName: r.partyName,
        particular: r.note || r.description, amount: r.amount, balanceAfter: 0,
      })
    } else if (r.kind === 'donation' && r.donationId) {
      const totals = await donorReceiptTotals(r.donationId)
      setViewReceipt({
        kind: 'donation', receiptNo: r.donationVoucherNo ?? '—',
        date: r.date, systemLabel: systemLabels[system], accountName: r.partyName,
        particular: r.description, amount: r.amount,
        balanceAfter: totals.totalContributed, announcedRemaining: totals.announcedRemaining,
        projectName: totals.projectName,
      isConfirmed: totals.isConfirmed,
      })
    }
  }

  const deleteTarget = async () => {
    if (!confirmDelete) return
    const table = confirmDelete.kind === 'payment' ? 'payments'
      : confirmDelete.kind === 'voucher' ? 'vouchers'
        : confirmDelete.kind === 'donation' ? 'donors' : 'bills'
    const { error } = await supabase.from(table).delete().eq('id', confirmDelete.id)
    setConfirmDelete(null)
    if (error) { toast.error(friendlyError(error)); return }
    toast.success('Deleted')
    load()
  }

  // A bill with cash already received cannot be deleted — the database refuses.
  // Name the receipts blocking it up front instead of surfacing a generic
  // constraint error after the click.
  const attemptDeleteBill = async (billId: string) => {
    const { data: pays } = await supabase.from('payments').select('receipt_no').eq('bill_id', billId).order('created_at')
    if (pays && pays.length > 0) {
      setBillDeleteBlock(pays.map((p) => p.receipt_no).filter(Boolean) as string[])
      return
    }
    setConfirmDelete({ kind: 'bill', id: billId })
  }

  return (
    <>
      <div className="flex items-center justify-between mb-6 gap-4 flex-wrap">
        <h1 className="font-heading text-[28px] font-bold leading-[36px] text-dp-primary">{t('tx.title')}</h1>
        {!access.loading && (access.canWaterSupply || access.canDonorsProjects) && (
          <div className="flex items-center gap-1 bg-dp-surface-container-low rounded-lg p-1">
            {access.canWaterSupply && (
              <button onClick={() => setSystem('water_supply')} className={`px-3 py-1.5 rounded-md text-[13px] font-sans font-semibold cursor-pointer transition-all ${system === 'water_supply' ? 'bg-dp-secondary text-white' : 'text-dp-on-surface-variant'}`}>{t('a.waterSupply')}</button>
            )}
            {access.canDonorsProjects && (
              <button onClick={() => setSystem('donors_projects')} className={`px-3 py-1.5 rounded-md text-[13px] font-sans font-semibold cursor-pointer transition-all ${system === 'donors_projects' ? 'bg-dp-secondary text-white' : 'text-dp-on-surface-variant'}`}>{t('a.donorsProjects')}</button>
            )}
          </div>
        )}
      </div>

      <div className="bg-white rounded-lg border border-dp-outline-variant p-4 mb-4 space-y-3">
        <div className="flex flex-wrap items-end gap-3">
          <div>
            <label className="block font-sans text-[12px] font-semibold text-dp-on-surface-variant mb-1">{t('a.from')}</label>
            <input type="date" value={from} onChange={(e) => setFrom(e.target.value)} className="input-field !py-2 text-[14px]" />
          </div>
          <div>
            <label className="block font-sans text-[12px] font-semibold text-dp-on-surface-variant mb-1">To</label>
            <input type="date" value={to} onChange={(e) => setTo(e.target.value)} className="input-field !py-2 text-[14px]" />
          </div>
          <div>
            <label className="block font-sans text-[12px] font-semibold text-dp-on-surface-variant mb-1">{t('a.year')}</label>
            <select onChange={(e) => applyYear(e.target.value)} defaultValue="" className="input-field !py-2 text-[14px]">
              <option value="">{t('tx.jumpYear')}</option>
              {years.map((y) => <option key={y} value={y}>{y}</option>)}
            </select>
          </div>
          <button onClick={setCurrentMonth} className="px-3 py-2 border border-dp-outline-variant rounded-lg font-sans text-[13px] font-semibold text-dp-on-surface hover:bg-dp-surface-container-low transition-all cursor-pointer">
            {t('tx.thisMonth')}
          </button>
          <div>
            <label className="block font-sans text-[12px] font-semibold text-dp-on-surface-variant mb-1">{t('w.status')}</label>
            <select value={statusFilter} onChange={(e) => setStatusFilter(e.target.value as typeof statusFilter)} className="input-field !py-2 text-[14px]">
              <option value="all">{t('tx.allStatuses')}</option>
              <option value="paid">{t('w.paid')}</option>
              <option value="partial">{t('tx.partial')}</option>
              <option value="pending">{t('tx.pending')}</option>
              <option value="overdue">{t('tx.overdue')}</option>
            </select>
          </div>
          <div>
            <label className="block font-sans text-[12px] font-semibold text-dp-on-surface-variant mb-1">{t('a.type')}</label>
            <select value={kindFilter} onChange={(e) => setKindFilter(e.target.value)} className="input-field !py-2 text-[14px]">
              <option value="all">{t('tx.allTypes')}</option>
              <option value="bill">{t('tx.bills')}</option>
              <option value="payment">{t('tx.paymentsReceipts')}</option>
              {system === 'donors_projects' && <option value="donation">{t('tx.donations')}</option>}
              {system === 'water_supply' && <option value="purchase">{t('tx.purchases')}</option>}
              <option value="voucher:expense">{t('tx.expenseVouchers')}</option>
              <option value="voucher:income">{t('tx.incomeVouchers')}</option>
              <option value="voucher:contra">{t('tx.bankTransfers')}</option>
              <option value="voucher:withdrawal">{t('tx.cashWithdrawals')}</option>
              <option value="voucher:deposit">{t('tx.cashDeposits')}</option>
              <option value="voucher:advance">{t('tx.advancePayments')}</option>
              <option value="voucher:security_deposit">{t('tx.securityDeposits')}</option>
              <option value="voucher:security_deposit_refund">{t('tx.depositRefunds')}</option>
            </select>
          </div>
          <div>
            <label className="block font-sans text-[12px] font-semibold text-dp-on-surface-variant mb-1">&nbsp;</label>
            <button
              onClick={() => setAutoPostedOnly(!autoPostedOnly)}
              title="Vouchers/purchases that posted after 24 hours without every approver confirming"
              className={`px-3 py-2 rounded-lg font-sans text-[13px] font-semibold transition-all cursor-pointer border ${autoPostedOnly ? 'bg-amber-100 border-amber-400 text-amber-900' : 'border-dp-outline-variant text-dp-on-surface hover:bg-dp-surface-container-low'}`}
            >
              {t('tx.autoPostedOnly')}
            </button>
          </div>
          <div className="flex-1 min-w-[220px]">
            <label className="block font-sans text-[12px] font-semibold text-dp-on-surface-variant mb-1">Search</label>
            <div className="relative">
              <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-dp-on-surface-variant pointer-events-none" />
              <input
                value={search} onChange={(e) => setSearch(e.target.value)}
                placeholder="Name, account ID, phone, receipt/voucher #, method..."
                className="input-field !py-2 !ps-9 text-[14px]"
              />
            </div>
          </div>
        </div>
        <p className="font-sans text-[12px] text-dp-on-surface-variant">Showing {filteredRows.length} of {rows.length} transactions in this date range. Widen the date range or jump to a year for older activity — only the current month loads by default.</p>
      </div>

      <div className="bg-white rounded-lg border border-dp-outline-variant overflow-hidden">
        {loading && <p className="px-4 py-8 text-center text-dp-on-surface-variant font-sans text-[13.5px]">{t('action.loading')}</p>}
        {!loading && filteredRows.length === 0 && <p className="px-4 py-8 text-center text-dp-on-surface-variant font-sans text-[13.5px]">{t('tx.noMatch')}</p>}
        <div className="divide-y divide-dp-outline-variant">
          {!loading && filteredRows.map((r) => (
            <div key={r.id} className={`flex border-s-[3px] ${r.borderColor}`}>
              <div className="flex-1 min-w-0 p-3.5">
                <div className="flex justify-between items-start gap-3">
                  <div className="min-w-0">
                    {r.typeLabel && <p className="font-sans text-[11.5px] text-dp-on-surface-variant leading-tight">{r.typeLabel}</p>}
                    <p className="font-sans text-[14px] font-bold text-dp-on-surface truncate">{r.partyName}</p>
                    {r.isRecurring && (
                      <span className="inline-block mt-0.5 me-1 px-1.5 py-0.5 rounded font-sans text-[10px] font-bold uppercase tracking-wide bg-indigo-100 text-indigo-700" title="Generated automatically by a recurring schedule, not entered by hand">
                        {t('a.recurring')}
                      </span>
                    )}
                    {r.autoPosted && (
                      <span className="inline-block mt-0.5 px-1.5 py-0.5 rounded font-sans text-[10px] font-bold uppercase tracking-wide bg-amber-100 text-amber-800" title="Posted after 24 hours without every approver confirming">
                        {t('a.autoPosted')}
                      </span>
                    )}
                    {r.fullyApproved && (
                      <span className="inline-block mt-0.5 px-1.5 py-0.5 rounded font-sans text-[10px] font-bold uppercase tracking-wide bg-emerald-100 text-emerald-800" title="Confirmed by every configured approver">
                        {t('f.approved')}
                      </span>
                    )}
                  </div>
                  <div className="text-end shrink-0">
                    <p className="font-sans text-[13px] font-bold text-dp-on-surface whitespace-nowrap">{r.docLabel}</p>
                    <p className="font-sans text-[12px] text-dp-on-surface-variant whitespace-nowrap">{new Date(r.date).toLocaleDateString('en-GB')}</p>
                  </div>
                </div>
                <div className="flex justify-between items-end gap-3 mt-1.5">
                  <p className="font-sans text-[13px] text-dp-on-surface-variant truncate">{r.description}</p>
                  <div className="text-end shrink-0">
                    {r.amount > 0 && <p className="font-sans text-[15px] font-bold text-dp-on-surface whitespace-nowrap">Rs {fmtAmount(r.amount)}</p>}
                    {r.badge && (
                      <span className={`inline-block mt-1 px-2 py-0.5 rounded font-sans text-[10.5px] font-bold tracking-wide ${billBadgeClass[r.badge.tone]}`}>{r.badge.text}</span>
                    )}
                  </div>
                </div>
                {(r.billId || r.kind === 'payment' || r.kind === 'voucher' || r.kind === 'purchase' || r.kind === 'donation') && (
                  <div className="flex justify-end items-center gap-1 mt-2 pt-2 border-t border-dp-outline-variant/60">
                    {r.billId && (
                      <Link href={`/admin/invoice/bill/${r.billId}`} title="View invoice" className="p-1.5 text-dp-on-surface-variant hover:text-dp-secondary cursor-pointer"><FileText size={15} /></Link>
                    )}
                    {(r.kind === 'payment' || r.kind === 'voucher' || r.kind === 'purchase' || r.kind === 'donation') && (
                      <button onClick={() => openRowReceipt(r)} title="View receipt" className="p-1.5 text-dp-on-surface-variant hover:text-dp-secondary cursor-pointer"><Eye size={15} /></button>
                    )}

                    {/* Edit opens the screen that owns the record, so there is one
                        edit form per document type instead of a second copy here
                        that could drift out of step with it. */}
                    {r.kind === 'bill' && r.billId && (
                      <Link href={`/admin/finance/${system}?action=generate_bill&bill=${r.billId}`} title="Edit bill" className="p-1.5 text-dp-on-surface-variant hover:text-dp-primary cursor-pointer"><Pencil size={15} /></Link>
                    )}
                    {r.kind === 'payment' && r.paymentId && (
                      <Link href={`/admin/finance/${system}?edit_payment=${r.paymentId}`} title="Edit payment" className="p-1.5 text-dp-on-surface-variant hover:text-dp-primary cursor-pointer"><Pencil size={15} /></Link>
                    )}
                    {r.kind === 'donation' && r.donationId && (
                      <Link href={`/admin/donors?edit=${r.donationId}`} title={r.donationVerified ? 'Edit donation' : 'Review & confirm'} className="p-1.5 text-dp-on-surface-variant hover:text-dp-primary cursor-pointer"><Pencil size={15} /></Link>
                    )}
                    {r.kind === 'voucher' && r.voucherId && (
                      <Link href={`/admin/finance/${system}?edit_voucher=${r.voucherId}`} title="Edit voucher" className="p-1.5 text-dp-on-surface-variant hover:text-dp-primary cursor-pointer"><Pencil size={15} /></Link>
                    )}

                    {r.kind === 'bill' && r.billId && (
                      <button onClick={() => attemptDeleteBill(r.billId!)} title="Delete bill" className="p-1.5 text-dp-on-surface-variant hover:text-dp-error cursor-pointer"><Trash2 size={15} /></button>
                    )}
                    {r.kind === 'payment' && r.paymentId && (
                      <button onClick={() => setConfirmDelete({ kind: 'payment', id: r.paymentId! })} title="Delete payment" className="p-1.5 text-dp-on-surface-variant hover:text-dp-error cursor-pointer"><Trash2 size={15} /></button>
                    )}
                    {r.kind === 'voucher' && r.voucherId && (
                      <button onClick={() => setConfirmDelete({ kind: 'voucher', id: r.voucherId! })} title="Delete voucher" className="p-1.5 text-dp-on-surface-variant hover:text-dp-error cursor-pointer"><Trash2 size={15} /></button>
                    )}
                    {r.kind === 'donation' && r.donationId && (
                      <button onClick={() => setConfirmDelete({ kind: 'donation', id: r.donationId! })} title="Delete donation" className="p-1.5 text-dp-on-surface-variant hover:text-dp-error cursor-pointer"><Trash2 size={15} /></button>
                    )}
                  </div>
                )}
              </div>
            </div>
          ))}
        </div>
      </div>
      {viewReceipt && <ReceiptModal data={viewReceipt} system={system} onClose={() => setViewReceipt(null)} />}

      <ConfirmDialog
        open={!!confirmDelete}
        title={`Delete ${confirmDelete?.kind ?? ''}`}
        message="Every ledger entry this created will be removed with it. This cannot be undone."
        onConfirm={deleteTarget}
        onCancel={() => setConfirmDelete(null)}
      />

      <ConfirmDialog
        open={!!billDeleteBlock}
        title="Bill Cannot Be Deleted"
        message={`Cash has already been received against this bill${billDeleteBlock?.length ? ` (receipt ${billDeleteBlock.join(', ')})` : ''}. Delete the receipt first, then the bill.`}
        confirmLabel="OK"
        onConfirm={() => setBillDeleteBlock(null)}
        onCancel={() => setBillDeleteBlock(null)}
      />
    </>
  )
}
