-- Migration 097: Complaint-linked bill waiver + automatic reconnection.
--
-- A water-supply complaint had no link to a specific consumer — only free-text
-- complainant_name/phone/sector. When a consumer genuinely has no/short water
-- access, the committee needs a way to waive their dues (Full or a Custom %)
-- for as long as the complaint stays open, without editing the original bill
-- (which must stand as billed — the waiver is a separate credit against the
-- consumer's account, same principle as security_deposit_refund crediting a
-- consumer account elsewhere in this schema).
--
-- The waiver auto-continues on every bill generated by the recurring schedule
-- while the complaint is open (not a per-month manual re-check), and stops the
-- moment the complaint is verified/closed or the consumer is disconnected.
-- Each waiver posts as its own single-leg 'complaint_waiver' voucher (own
-- counter/prefix, WS-CW-V) rather than folding into 'expense' the way
-- advance_settlement was (migration 090) — the committee wants this visible
-- as its own category. It goes through the exact same approval gate as any
-- other cash-out voucher (voucher_requires_approval), no new approval
-- machinery.
--
-- Separately: disconnect_consumer() (migration 071) is explicitly one-way —
-- "so they can't be silently reactivated." This adds the missing other half:
-- once a disconnected consumer's ledger balance clears (e.g. they pay off
-- what deposit-netting didn't cover), they're automatically reactivated. The
-- hook point is AFTER INSERT ON ledger_entries itself — that table currently
-- has zero triggers of its own — rather than duplicating the check across the
-- four separate source triggers (bills/payments/vouchers/donations) that all
-- write into it.

-- 1. Schema additions.
ALTER TABLE complaints ADD COLUMN IF NOT EXISTS consumer_id varchar REFERENCES consumers(consumer_id);
ALTER TABLE complaints ADD COLUMN IF NOT EXISTS waiver_active boolean NOT NULL DEFAULT false;
ALTER TABLE complaints ADD COLUMN IF NOT EXISTS waiver_type varchar CHECK (waiver_type IN ('full', 'percent'));
ALTER TABLE complaints ADD COLUMN IF NOT EXISTS waiver_percent numeric CHECK (waiver_percent > 0 AND waiver_percent <= 100);
ALTER TABLE complaints ADD COLUMN IF NOT EXISTS waiver_set_by uuid REFERENCES admin_users(id);
ALTER TABLE complaints ADD COLUMN IF NOT EXISTS waiver_set_at timestamptz;
CREATE INDEX IF NOT EXISTS complaints_consumer_idx ON complaints(consumer_id);
-- At most one complaint per consumer can have an active waiver at a time —
-- keeps apply_complaint_waiver_to_bill's no-op-if-already-waived guard from
-- having to arbitrate between two simultaneously "genuine" complaints.
CREATE UNIQUE INDEX IF NOT EXISTS complaints_one_active_waiver_per_consumer
  ON complaints(consumer_id) WHERE waiver_active = true;

ALTER TABLE bills ADD COLUMN IF NOT EXISTS waiver_voucher_id uuid REFERENCES vouchers(id);
ALTER TABLE bills ADD COLUMN IF NOT EXISTS waiver_type varchar;
ALTER TABLE bills ADD COLUMN IF NOT EXISTS waiver_percent numeric;
ALTER TABLE bills ADD COLUMN IF NOT EXISTS waiver_complaint_id uuid REFERENCES complaints(id);
CREATE INDEX IF NOT EXISTS bills_waiver_complaint_idx ON bills(waiver_complaint_id);

INSERT INTO accounts (code, name, type, system, description, is_protected)
VALUES ('WS-3010', 'Complaint Bill Waivers', 'expense', 'water_supply',
  'Dues waived by committee decision on genuine service-failure complaints', true)
ON CONFLICT (code, system) DO NOTHING;

ALTER TABLE vouchers DROP CONSTRAINT IF EXISTS vouchers_voucher_type_check;
ALTER TABLE vouchers ADD CONSTRAINT vouchers_voucher_type_check
  CHECK (voucher_type IN ('expense', 'income', 'contra', 'withdrawal', 'deposit',
    'security_deposit', 'security_deposit_refund', 'advance', 'advance_settlement', 'complaint_waiver'));

INSERT INTO voucher_counters (system, voucher_type, prefix)
VALUES ('water_supply', 'complaint_waiver', 'WS-CW-V')
ON CONFLICT (system, voucher_type) DO NOTHING;

-- 2. Widen the approval gate to cover the new type — same bucket as expense.
CREATE OR REPLACE FUNCTION voucher_requires_approval(p_system varchar, p_voucher_type varchar) RETURNS boolean AS $$
DECLARE
  v_requires boolean;
  v_has_approvers boolean;
BEGIN
  v_requires := p_voucher_type IN ('withdrawal', 'expense', 'advance', 'advance_settlement', 'complaint_waiver')
    AND approval_type_enabled(p_system, CASE WHEN p_voucher_type = 'withdrawal' THEN 'withdrawal' ELSE 'expense' END);
  IF v_requires THEN
    SELECT EXISTS(SELECT 1 FROM approval_approvers WHERE system = p_system AND is_active = true) INTO v_has_approvers;
    v_requires := v_has_approvers;
  END IF;
  RETURN v_requires;
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public;

-- 3. post_voucher_ledger_legs — unchanged from migration 083/090 except the
-- new trailing block that credits the waived bill's paid_amount/status the
-- same way trg_payment_ledger (089) already does for a real payment, so
-- src/lib/billStatus.ts's badge computation (purely a function of amount_pkr/
-- discount_amount/paid_amount — no separate "waived" status value needed)
-- picks it up automatically. Fires once, on whichever of the two paths this
-- voucher actually posts through (immediate, or later via approval) — both
-- already funnel through this one function.
CREATE OR REPLACE FUNCTION post_voucher_ledger_legs(p_voucher vouchers) RETURNS void AS $$
DECLARE
  v_bill_number varchar;
  v_line_total decimal;
  v_advance_amount decimal;
  v_diff decimal;
  v_advance_account_id uuid;
  r RECORD;
BEGIN
  IF p_voucher.bill_id IS NOT NULL THEN
    SELECT bill_number INTO v_bill_number FROM bills WHERE id = p_voucher.bill_id;
  END IF;

  SELECT COALESCE(SUM(amount), 0) INTO v_line_total FROM voucher_line_items WHERE voucher_id = p_voucher.id;

  IF p_voucher.voucher_type = 'advance_settlement' THEN
    FOR r IN SELECT account_id, amount, description FROM voucher_line_items WHERE voucher_id = p_voucher.id LOOP
      INSERT INTO ledger_entries (account_id, entry_date, particular, debit, credit, reference_type, reference_id, receipt_no, bill_number)
      VALUES (r.account_id, p_voucher.voucher_date, COALESCE(r.description, p_voucher.particular), r.amount, 0, 'voucher', p_voucher.id, p_voucher.receipt_no, v_bill_number);
    END LOOP;

    SELECT amount_pkr INTO v_advance_amount FROM vouchers WHERE id = p_voucher.settles_voucher_id;
    v_diff := v_advance_amount - v_line_total; -- > 0: refund received; < 0: extra paid

    SELECT id INTO v_advance_account_id FROM accounts WHERE system = p_voucher.system AND code = 'WS-4003';
    INSERT INTO ledger_entries (account_id, entry_date, particular, debit, credit, reference_type, reference_id, receipt_no, bill_number)
    VALUES (v_advance_account_id, p_voucher.voucher_date, p_voucher.particular, 0, v_advance_amount, 'voucher', p_voucher.id, p_voucher.receipt_no, v_bill_number);

    IF v_diff > 0 THEN
      INSERT INTO ledger_entries (account_id, entry_date, particular, debit, credit, reference_type, reference_id, receipt_no, bill_number)
      VALUES (p_voucher.from_account_id, p_voucher.voucher_date, p_voucher.particular, v_diff, 0, 'voucher', p_voucher.id, p_voucher.receipt_no, v_bill_number);
    ELSIF v_diff < 0 THEN
      INSERT INTO ledger_entries (account_id, entry_date, particular, debit, credit, reference_type, reference_id, receipt_no, bill_number)
      VALUES (p_voucher.from_account_id, p_voucher.voucher_date, p_voucher.particular, 0, -v_diff, 'voucher', p_voucher.id, p_voucher.receipt_no, v_bill_number);
    END IF;

    UPDATE vouchers SET settled_at = now() WHERE id = p_voucher.settles_voucher_id;

  ELSIF v_line_total > 0 THEN
    FOR r IN SELECT account_id, amount, description FROM voucher_line_items WHERE voucher_id = p_voucher.id LOOP
      INSERT INTO ledger_entries (account_id, entry_date, particular, debit, credit, reference_type, reference_id, receipt_no, bill_number)
      VALUES (r.account_id, p_voucher.voucher_date, COALESCE(r.description, p_voucher.particular), r.amount, 0, 'voucher', p_voucher.id, p_voucher.receipt_no, v_bill_number);
    END LOOP;
    INSERT INTO ledger_entries (account_id, entry_date, particular, debit, credit, reference_type, reference_id, receipt_no, bill_number)
    VALUES (p_voucher.from_account_id, p_voucher.voucher_date, p_voucher.particular, 0, v_line_total, 'voucher', p_voucher.id, p_voucher.receipt_no, v_bill_number);

  ELSE
    INSERT INTO ledger_entries (account_id, entry_date, particular, debit, credit, reference_type, reference_id, receipt_no, bill_number)
    VALUES (p_voucher.to_account_id, p_voucher.voucher_date, p_voucher.particular, p_voucher.amount_pkr, 0, 'voucher', p_voucher.id, p_voucher.receipt_no, v_bill_number);
    INSERT INTO ledger_entries (account_id, entry_date, particular, debit, credit, reference_type, reference_id, receipt_no, bill_number)
    VALUES (p_voucher.from_account_id, p_voucher.voucher_date, p_voucher.particular, 0, p_voucher.amount_pkr, 'voucher', p_voucher.id, p_voucher.receipt_no, v_bill_number);
  END IF;

  IF p_voucher.voucher_type = 'complaint_waiver' AND p_voucher.bill_id IS NOT NULL THEN
    UPDATE bills b SET
      paid_amount = COALESCE(b.paid_amount, 0) + p_voucher.amount_pkr,
      status = CASE
        WHEN COALESCE(b.paid_amount, 0) + p_voucher.amount_pkr >= (b.amount_pkr - COALESCE(b.discount_amount, 0)) THEN 'paid'
        WHEN COALESCE(b.paid_amount, 0) + p_voucher.amount_pkr > 0 THEN 'partial'
        ELSE b.status
      END
    WHERE b.id = p_voucher.bill_id;
  END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- 4. The waiver itself — a plain single-leg voucher (no draft/line-items
-- needed, since each waiver always targets exactly one bill via vouchers.bill_id,
-- which already exists). No-ops if the bill is already waived, already fully
-- settled, or the complaint's waiver isn't actually active — safe to call
-- both from set_complaint_waiver (below) and from run_recurring_schedule.
CREATE OR REPLACE FUNCTION apply_complaint_waiver_to_bill(p_bill_id uuid, p_complaint_id uuid) RETURNS void AS $$
DECLARE
  v_bill bills%ROWTYPE;
  v_complaint complaints%ROWTYPE;
  v_net_payable decimal;
  v_remaining decimal;
  v_waiver_amount decimal;
  v_consumer_account_id uuid;
  v_waiver_account_id uuid;
  v_consumer_name varchar;
  v_voucher_id uuid;
BEGIN
  SELECT * INTO v_bill FROM bills WHERE id = p_bill_id;
  IF v_bill.id IS NULL OR v_bill.waiver_voucher_id IS NOT NULL THEN RETURN; END IF;

  SELECT * INTO v_complaint FROM complaints WHERE id = p_complaint_id;
  IF v_complaint.id IS NULL OR v_complaint.waiver_active IS NOT TRUE OR v_complaint.consumer_id IS DISTINCT FROM v_bill.consumer_id THEN
    RETURN;
  END IF;

  v_net_payable := v_bill.amount_pkr - COALESCE(v_bill.discount_amount, 0);
  v_remaining := GREATEST(v_net_payable - COALESCE(v_bill.paid_amount, 0), 0);
  IF v_remaining <= 0 THEN RETURN; END IF;

  v_waiver_amount := CASE WHEN v_complaint.waiver_type = 'full' THEN v_remaining
                          ELSE round(v_net_payable * v_complaint.waiver_percent / 100, 2) END;
  v_waiver_amount := LEAST(v_waiver_amount, v_remaining);
  IF v_waiver_amount <= 0 THEN RETURN; END IF;

  SELECT id, name INTO v_consumer_account_id, v_consumer_name FROM accounts WHERE type = 'consumer' AND consumer_id = v_bill.consumer_id;
  SELECT id INTO v_waiver_account_id FROM accounts WHERE system = 'water_supply' AND code = 'WS-3010';
  IF v_consumer_account_id IS NULL OR v_waiver_account_id IS NULL THEN RETURN; END IF;

  INSERT INTO vouchers (system, voucher_type, voucher_date, particular, amount_pkr, from_account_id, to_account_id, bill_id, consumer_id, party_name)
  VALUES ('water_supply', 'complaint_waiver', current_date,
    'Complaint waiver (' || CASE WHEN v_complaint.waiver_type = 'full' THEN 'Full' ELSE v_complaint.waiver_percent || '%' END
      || ') — ' || v_complaint.complaint_number || ' — Bill #' || v_bill.bill_number,
    v_waiver_amount, v_consumer_account_id, v_waiver_account_id, p_bill_id, v_bill.consumer_id, v_consumer_name)
  RETURNING id INTO v_voucher_id;

  UPDATE bills SET
    waiver_voucher_id = v_voucher_id,
    waiver_type = v_complaint.waiver_type, waiver_percent = v_complaint.waiver_percent, waiver_complaint_id = p_complaint_id
  WHERE id = p_bill_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- 5. Committee decision — permission-gated identically to verify_complaint()
-- (can_verify_complaints or super_admin), since this is the same "genuine
-- complaint, committee has decided" tier of judgment.
CREATE OR REPLACE FUNCTION set_complaint_waiver(p_complaint_id uuid, p_active boolean, p_waiver_type varchar, p_waiver_percent numeric) RETURNS void AS $$
DECLARE
  v_complaint complaints%ROWTYPE;
  v_note text;
  r record;
BEGIN
  IF current_admin_role() IS DISTINCT FROM 'super_admin'
     AND COALESCE((SELECT can_verify_complaints FROM admin_users WHERE id = current_admin_user_id()), false) IS DISTINCT FROM true THEN
    RAISE EXCEPTION 'You are not authorized to set a bill waiver on this complaint.';
  END IF;

  SELECT * INTO v_complaint FROM complaints WHERE id = p_complaint_id;
  IF v_complaint.id IS NULL THEN RAISE EXCEPTION 'Complaint not found.'; END IF;
  IF v_complaint.consumer_id IS NULL THEN RAISE EXCEPTION 'Link this complaint to a consumer before setting a waiver.'; END IF;

  IF p_active THEN
    IF p_waiver_type NOT IN ('full', 'percent') THEN RAISE EXCEPTION 'Choose Full or Percent.'; END IF;
    IF p_waiver_type = 'percent' AND (p_waiver_percent IS NULL OR p_waiver_percent <= 0 OR p_waiver_percent > 100) THEN
      RAISE EXCEPTION 'Enter a waiver percentage between 1 and 100.';
    END IF;

    UPDATE complaints SET waiver_active = true, waiver_type = p_waiver_type,
      waiver_percent = CASE WHEN p_waiver_type = 'percent' THEN p_waiver_percent ELSE NULL END,
      waiver_set_by = current_admin_user_id(), waiver_set_at = now()
    WHERE id = p_complaint_id;

    v_note := 'Bill waiver set: ' || CASE WHEN p_waiver_type = 'full' THEN 'Full waiver' ELSE p_waiver_percent || '% waiver' END
      || ' — dues will be waived on the pending bill and every future bill while this complaint remains open.';
    INSERT INTO complaint_updates (complaint_id, author_id, kind, body) VALUES (p_complaint_id, current_admin_user_id(), 'comment', v_note);

    FOR r IN SELECT id FROM bills WHERE consumer_id = v_complaint.consumer_id AND status IN ('unpaid', 'pending', 'late', 'partial') AND waiver_voucher_id IS NULL LOOP
      PERFORM apply_complaint_waiver_to_bill(r.id, p_complaint_id);
    END LOOP;
  ELSE
    UPDATE complaints SET waiver_active = false WHERE id = p_complaint_id;
    INSERT INTO complaint_updates (complaint_id, author_id, kind, body) VALUES (p_complaint_id, current_admin_user_id(), 'comment', 'Bill waiver cleared — future bills will be billed normally.');
  END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE ALL ON FUNCTION set_complaint_waiver(uuid, boolean, varchar, numeric) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION set_complaint_waiver(uuid, boolean, varchar, numeric) TO authenticated;

-- 6. run_recurring_schedule — unchanged from migration 082 except the new
-- "auto-continue" hook right after a bill is generated.
CREATE OR REPLACE FUNCTION run_recurring_schedule(p_schedule_id uuid) RETURNS void AS $$
DECLARE
  s recurring_schedules%ROWTYPE;
  v_new_id uuid;
  v_next timestamptz;
  v_due_date date;
  v_complaint record;
BEGIN
  SELECT * INTO s FROM recurring_schedules
  WHERE id = p_schedule_id AND is_active = true AND next_run_date <= now()
  FOR UPDATE;
  IF NOT FOUND THEN RETURN; END IF;

  v_due_date := make_date(EXTRACT(YEAR FROM s.next_run_date)::int, EXTRACT(MONTH FROM s.next_run_date)::int, 7);

  IF s.schedule_type = 'bill' THEN
    INSERT INTO bills (consumer_id, month, year, amount_pkr, discount_amount, due_date, description, recurring_schedule_id)
    VALUES (s.consumer_id, EXTRACT(MONTH FROM s.next_run_date)::int, EXTRACT(YEAR FROM s.next_run_date)::int,
            s.amount_pkr, s.discount_amount, v_due_date, s.particular, s.id)
    ON CONFLICT (consumer_id, month, year) DO NOTHING
    RETURNING id INTO v_new_id;

    IF v_new_id IS NOT NULL THEN
      FOR v_complaint IN
        SELECT id FROM complaints WHERE system = 'water_supply' AND consumer_id = s.consumer_id AND status != 'verified' AND waiver_active = true
      LOOP
        PERFORM apply_complaint_waiver_to_bill(v_new_id, v_complaint.id);
      END LOOP;
    END IF;

  ELSIF s.schedule_type = 'donation' THEN
    INSERT INTO donors (name, name_ur, phone, donor_type, amount_pkr, date, payment_method, project_id, is_verified, is_anonymous, recurring_schedule_id)
    VALUES (s.donor_name, s.donor_name_ur, s.donor_phone, s.donor_type, s.amount_pkr, s.next_run_date::date,
            s.payment_method, s.project_id, true, false, s.id)
    RETURNING id INTO v_new_id;

  ELSIF s.schedule_type = 'expense' THEN
    INSERT INTO vouchers (system, voucher_type, voucher_date, particular, amount_pkr, from_account_id, to_account_id, party_name, recurring_schedule_id)
    VALUES (s.system, 'expense', s.next_run_date::date, COALESCE(s.particular, 'Recurring expense'), s.amount_pkr,
            s.from_account_id, s.to_account_id, s.party_name, s.id)
    RETURNING id INTO v_new_id;
  END IF;

  v_next := CASE s.frequency
    WHEN 'every_minute' THEN s.next_run_date + INTERVAL '1 minute'
    WHEN 'daily' THEN s.next_run_date + INTERVAL '1 day'
    WHEN 'weekly' THEN s.next_run_date + INTERVAL '7 days'
    WHEN 'monthly' THEN s.next_run_date + INTERVAL '1 month'
    WHEN 'semi_annual' THEN s.next_run_date + INTERVAL '6 months'
    WHEN 'yearly' THEN s.next_run_date + INTERVAL '1 year'
  END;

  UPDATE recurring_schedules SET
    next_run_date = v_next,
    last_run_at = now(),
    last_generated_type = s.schedule_type,
    last_generated_id = v_new_id
  WHERE id = p_schedule_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- 7. verify_complaint — unchanged from migration 063 except clearing the
-- waiver once the complaint is closed for good.
CREATE OR REPLACE FUNCTION verify_complaint(p_complaint_id uuid, p_note text) RETURNS void AS $$
DECLARE v_complaint complaints%ROWTYPE;
BEGIN
  IF current_admin_role() IS DISTINCT FROM 'super_admin'
     AND COALESCE((SELECT can_verify_complaints FROM admin_users WHERE id = current_admin_user_id()), false) IS DISTINCT FROM true THEN
    RAISE EXCEPTION 'You are not authorized to verify complaints.';
  END IF;
  SELECT * INTO v_complaint FROM complaints WHERE id = p_complaint_id;
  IF v_complaint.id IS NULL THEN RAISE EXCEPTION 'Complaint not found.'; END IF;
  IF v_complaint.status IS DISTINCT FROM 'awaiting_verification' THEN
    RAISE EXCEPTION 'This complaint is not awaiting verification.';
  END IF;

  UPDATE complaints SET status = 'verified', verified_at = now(), verified_by = current_admin_user_id(), waiver_active = false WHERE id = p_complaint_id;
  INSERT INTO complaint_updates (complaint_id, author_id, kind, body)
  VALUES (p_complaint_id, current_admin_user_id(), 'comment', COALESCE(NULLIF(trim(p_note), ''), 'Verified and closed.'));
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- 8. disconnect_consumer — unchanged from migration 092 except clearing any
-- active waiver on this consumer's complaints (permanent disconnection is the
-- other explicit cutoff, per the user's stated rule).
CREATE OR REPLACE FUNCTION disconnect_consumer(p_consumer_id varchar) RETURNS jsonb AS $$
DECLARE
  v_consumer_account_id uuid;
  v_deposit_account_id uuid;
  v_cash_account_id uuid;
  v_consumer_name varchar;
  v_deposit_on_hand decimal;
  v_pending_balance decimal;
  v_applied decimal;
  v_refund decimal;
BEGIN
  IF NOT current_admin_permission('manage_parties') THEN
    RAISE EXCEPTION 'Only a user with consumer-management permission can disconnect a consumer';
  END IF;

  SELECT id, name INTO v_consumer_account_id, v_consumer_name FROM accounts WHERE type = 'consumer' AND consumer_id = p_consumer_id;
  IF v_consumer_account_id IS NULL THEN
    RAISE EXCEPTION 'No ledger account found for consumer %', p_consumer_id;
  END IF;

  SELECT id INTO v_deposit_account_id FROM accounts WHERE system = 'water_supply' AND code = 'WS-5002';
  SELECT id INTO v_cash_account_id FROM accounts WHERE system = 'water_supply' AND code = 'WS-1001';

  SELECT COALESCE(SUM(v.amount_pkr), 0) INTO v_deposit_on_hand
  FROM vouchers v WHERE v.voucher_type = 'security_deposit' AND v.status = 'posted'
    AND v.bill_id IN (SELECT id FROM bills WHERE consumer_id = p_consumer_id);
  v_deposit_on_hand := v_deposit_on_hand - COALESCE((
    SELECT SUM(v.amount_pkr) FROM vouchers v
    WHERE v.voucher_type = 'security_deposit_refund' AND v.status = 'posted' AND v.consumer_id = p_consumer_id
  ), 0);

  SELECT a.opening_balance + COALESCE((SELECT SUM(l.debit - l.credit) FROM ledger_entries l WHERE l.account_id = a.id), 0)
  INTO v_pending_balance FROM accounts a WHERE a.id = v_consumer_account_id;

  v_applied := LEAST(v_deposit_on_hand, GREATEST(v_pending_balance, 0));
  v_refund := v_deposit_on_hand - v_applied;

  IF v_applied > 0 AND v_deposit_account_id IS NOT NULL THEN
    INSERT INTO vouchers (system, voucher_type, voucher_date, particular, amount_pkr, from_account_id, to_account_id, consumer_id, party_name)
    VALUES ('water_supply', 'security_deposit_refund', current_date,
      'Security deposit applied to outstanding balance — ' || v_consumer_name, v_applied,
      v_consumer_account_id, v_deposit_account_id, p_consumer_id, v_consumer_name);
  END IF;

  IF v_refund > 0 AND v_deposit_account_id IS NOT NULL AND v_cash_account_id IS NOT NULL THEN
    INSERT INTO vouchers (system, voucher_type, voucher_date, particular, amount_pkr, from_account_id, to_account_id, consumer_id, party_name)
    VALUES ('water_supply', 'security_deposit_refund', current_date,
      'Security deposit refund — ' || v_consumer_name, v_refund,
      v_cash_account_id, v_deposit_account_id, p_consumer_id, v_consumer_name);
  END IF;

  UPDATE consumers SET status = 'disconnected', disconnected_at = now() WHERE consumer_id = p_consumer_id;
  UPDATE accounts SET is_active = false WHERE id = v_consumer_account_id;
  UPDATE recurring_schedules SET is_active = false
    WHERE consumer_id = p_consumer_id AND schedule_type = 'bill' AND is_active = true;
  UPDATE complaints SET waiver_active = false WHERE consumer_id = p_consumer_id AND waiver_active = true;

  RETURN jsonb_build_object(
    'deposit_on_hand', v_deposit_on_hand, 'pending_balance', v_pending_balance,
    'applied', v_applied, 'refund', v_refund
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- 9. Automatic reconnection — the missing other half of disconnect_consumer().
-- Hooked onto ledger_entries itself (no existing trigger there) so it
-- uniformly covers every way a disconnected consumer's balance could clear
-- (a direct payment, a manual voucher credit, anything) without duplicating
-- this check across bills/payments/vouchers/donations' own triggers.
CREATE OR REPLACE FUNCTION trg_ledger_entry_check_reconnect() RETURNS trigger AS $$
DECLARE
  v_consumer_id varchar;
  v_status varchar;
  v_balance decimal;
BEGIN
  SELECT a.consumer_id, c.status INTO v_consumer_id, v_status
  FROM accounts a JOIN consumers c ON c.consumer_id = a.consumer_id
  WHERE a.id = NEW.account_id AND a.type = 'consumer';

  IF v_consumer_id IS NULL OR v_status IS DISTINCT FROM 'disconnected' THEN
    RETURN NEW;
  END IF;

  SELECT a.opening_balance + COALESCE((SELECT SUM(l.debit - l.credit) FROM ledger_entries l WHERE l.account_id = a.id), 0)
  INTO v_balance FROM accounts a WHERE a.id = NEW.account_id;

  IF v_balance <= 0 THEN
    UPDATE consumers SET status = 'active', disconnected_at = NULL WHERE consumer_id = v_consumer_id;
    UPDATE accounts SET is_active = true WHERE id = NEW.account_id;
    UPDATE recurring_schedules SET is_active = true,
      next_run_date = CASE WHEN next_run_date <= now() THEN now() ELSE next_run_date END
      WHERE consumer_id = v_consumer_id AND schedule_type = 'bill' AND is_active = false;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

DROP TRIGGER IF EXISTS ledger_entry_check_reconnect_trigger ON ledger_entries;
CREATE TRIGGER ledger_entry_check_reconnect_trigger AFTER INSERT ON ledger_entries
  FOR EACH ROW EXECUTE FUNCTION trg_ledger_entry_check_reconnect();
