-- Migration 175: let a posted voucher be corrected in place.
--
-- Why not the delete-then-reinsert trick that payment editing uses: a voucher
-- is not a payment.
--
--   * trg_voucher_before_insert() re-runs on any INSERT, so an already-approved
--     cash expense would come back as status='pending' with voucher_no wiped —
--     an approved, numbered document silently becoming unapproved and unnumbered.
--   * Seven foreign keys point at vouchers(id): voucher_line_items and
--     approval_confirmations (ON DELETE CASCADE, so their rows would be
--     destroyed), bills.security_deposit_voucher_id and bills.waiver_voucher_id
--     (ON DELETE SET NULL, so a deposit or waiver would quietly unlink from its
--     bill), plus settles_voucher_id, connection_requests and employee_payslips.
--     Reinserting mints a new id and breaks every one of them.
--
-- So this updates the row in place — same id, same voucher_no, same status and
-- approval history — and re-derives the two ledger entries from the new values.
-- All in one transaction: the books are never half-corrected.
CREATE OR REPLACE FUNCTION edit_voucher(
  p_voucher_id uuid,
  p_amount numeric,
  p_date date,
  p_particular text,
  p_party_name varchar,
  p_from_account_id uuid,
  p_to_account_id uuid
) RETURNS void AS $$
DECLARE
  v vouchers%ROWTYPE;
  v_from accounts%ROWTYPE;
  v_to accounts%ROWTYPE;
  v_lines int;
BEGIN
  SELECT * INTO v FROM vouchers WHERE id = p_voucher_id FOR UPDATE;
  IF v.id IS NULL THEN RAISE EXCEPTION 'Voucher not found'; END IF;

  IF NOT can_access_system(v.system) OR NOT current_admin_permission('post_transactions') THEN
    RAISE EXCEPTION 'Not authorized to edit this voucher';
  END IF;

  -- A voucher still in the approval queue was submitted at a particular amount;
  -- changing it underneath the approvers would defeat the gate. Delete and
  -- re-raise it instead.
  IF v.status IS DISTINCT FROM 'posted' THEN
    RAISE EXCEPTION 'Only a posted voucher can be edited — this one is %', COALESCE(v.status, 'unknown');
  END IF;

  -- Multi-line vouchers derive their total from voucher_line_items; editing the
  -- header amount alone would put the two out of step.
  SELECT count(*) INTO v_lines FROM voucher_line_items WHERE voucher_id = p_voucher_id;
  IF v_lines > 0 THEN
    RAISE EXCEPTION 'This voucher has itemised lines — edit it from the voucher form so the lines and the total stay in step';
  END IF;

  -- System-generated vouchers belong to the document that created them; editing
  -- one here would leave that document describing something that no longer
  -- matches.
  IF EXISTS (SELECT 1 FROM bills WHERE security_deposit_voucher_id = p_voucher_id OR waiver_voucher_id = p_voucher_id)
     OR EXISTS (SELECT 1 FROM connection_requests WHERE employee_charge_voucher_id = p_voucher_id)
     OR EXISTS (SELECT 1 FROM employee_payslips WHERE recognition_voucher_id = p_voucher_id)
     OR EXISTS (SELECT 1 FROM vouchers WHERE settles_voucher_id = p_voucher_id)
  THEN
    RAISE EXCEPTION 'This voucher was generated by another document (a bill, connection, payslip or settlement) — edit that document instead';
  END IF;

  IF p_amount IS NULL OR p_amount <= 0 THEN RAISE EXCEPTION 'Amount must be greater than zero'; END IF;
  IF p_from_account_id = p_to_account_id THEN RAISE EXCEPTION 'A voucher cannot move money to the same account it came from'; END IF;

  SELECT * INTO v_from FROM accounts WHERE id = p_from_account_id;
  SELECT * INTO v_to   FROM accounts WHERE id = p_to_account_id;
  IF v_from.id IS NULL OR v_to.id IS NULL THEN RAISE EXCEPTION 'Account not found'; END IF;
  IF v_from.system <> v.system OR v_to.system <> v.system THEN
    RAISE EXCEPTION 'Both accounts must belong to the % system', v.system;
  END IF;

  -- Recorded before the change so the original figures survive the correction.
  INSERT INTO audit_log (table_name, record_id, action, record_data, old_data, system, summary, actor_id, actor_name)
  VALUES (
    'vouchers', v.id, 'update',
    jsonb_build_object('amount_pkr', p_amount, 'voucher_date', p_date, 'particular', p_particular,
                       'party_name', p_party_name, 'from_account_id', p_from_account_id, 'to_account_id', p_to_account_id),
    to_jsonb(v), v.system,
    'Voucher ' || COALESCE(v.voucher_no, '(unnumbered)') || ' edited — Rs. ' || v.amount_pkr || ' → Rs. ' || p_amount,
    current_admin_user_id(), current_admin_name()
  );

  UPDATE vouchers SET
    amount_pkr = p_amount, voucher_date = p_date, particular = p_particular,
    party_name = p_party_name, from_account_id = p_from_account_id, to_account_id = p_to_account_id
  WHERE id = p_voucher_id;

  -- Re-derive the postings. There is no UPDATE trigger on vouchers (only INSERT
  -- and DELETE), which is exactly why editing was never safe to do from the
  -- client: the row would change and the ledger would not follow.
  DELETE FROM ledger_entries WHERE reference_type = 'voucher' AND reference_id = p_voucher_id;
  INSERT INTO ledger_entries (account_id, entry_date, particular, debit, credit, reference_type, reference_id)
  VALUES (p_to_account_id, p_date, p_particular, p_amount, 0, 'voucher', p_voucher_id);
  INSERT INTO ledger_entries (account_id, entry_date, particular, debit, credit, reference_type, reference_id)
  VALUES (p_from_account_id, p_date, p_particular, 0, p_amount, 'voucher', p_voucher_id);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE ALL ON FUNCTION edit_voucher(uuid, numeric, date, text, varchar, uuid, uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION edit_voucher(uuid, numeric, date, text, varchar, uuid, uuid) TO authenticated;
