-- Migration 230: the Kafalat measuring account.
--
-- ═════════════════════════════════════════════════════════════════════════
-- What this replaces
-- ═════════════════════════════════════════════════════════════════════════
-- pool_monthly_target() for kind='kafalat' summed every active child's full
-- annual package and divided by twelve, every time it was asked. Two things
-- were wrong with that: it ignored the calendar (a child joining in February
-- was still divided over twelve months as though the year had just started),
-- and it ignored what had already been raised (the figure never fell as
-- donors paid — it only ever reflected the roster).
--
-- The measuring account is that same figure, made real and visible instead of
-- recomputed silently. One account per academic year, sitting under the
-- Restricted Funds header beside the Kafalat fund itself so the committee can
-- open the chart of accounts and see it — but with no fund_type of its own,
-- so it can never be picked up by fund_account_id() or fund_balance() and
-- mistaken for money. It is a requirement register, not a wallet:
--
--   requirement rises   — a child is approved, or a rate is revised up
--   requirement falls    — a donor's payment is confirmed against it
--   outstanding           — what is still needed for the rest of THIS year
--   monthly figure         — outstanding ÷ months left in the year
--
-- Both legs of every posting land on accounts of type restricted_fund, which
-- migration 221's trigger already flags is_memo. It never appears in a trial
-- balance and never inflates a total that includes real cash.
--
-- ═════════════════════════════════════════════════════════════════════════
-- Why annual items are not pro-rated and monthly ones are
-- ═════════════════════════════════════════════════════════════════════════
-- A child who joins in August still needs a full uniform and a full set of
-- books today, not five-twelfths of one. Pro-rating those would fund a child
-- for a partial uniform and leave the committee to find the rest by hand.
-- School fee, transport and pocket money are genuinely monthly costs, so
-- those shrink to the months actually remaining. Each package line carries
-- which kind it is, defaulted sensibly by category and overridable per line.

ALTER TABLE kafalat_package_lines
  ADD COLUMN IF NOT EXISTS is_prorated boolean,
  -- 'auto' rows are regenerated by the rate card and replaced wholesale on
  -- every recalculation; 'manual' rows are a committee member's own figure
  -- and are never touched by the generator.
  ADD COLUMN IF NOT EXISTS source varchar NOT NULL DEFAULT 'manual'
    CHECK (source IN ('auto', 'manual'));

UPDATE kafalat_package_lines SET is_prorated =
  CASE category WHEN 'school_fee' THEN true WHEN 'transport' THEN true
                WHEN 'pocket_money' THEN true WHEN 'tuition' THEN true
                ELSE false END
WHERE is_prorated IS NULL;

ALTER TABLE kafalat_package_lines ALTER COLUMN is_prorated SET NOT NULL;
ALTER TABLE kafalat_package_lines ALTER COLUMN is_prorated SET DEFAULT false;

-- Kafalat covers class 1 through class 10 — above that a student is old
-- enough for Taleemi Wazifa, which is where migration 233's graduation
-- handoff sends them. Kept as settings rather than a hard-coded range, so the
-- committee can widen it without a migration.
INSERT INTO site_settings (key, value) VALUES
  ('kafalat_min_class', '1'), ('kafalat_max_class', '10')
ON CONFLICT (key) DO NOTHING;

-- ═════════════════════════════════════════════════════════════════════════
-- The academic year, as a calendar rather than a label
-- ═════════════════════════════════════════════════════════════════════════
-- The Punjab school year runs April to March. '2026-27' means 1 Apr 2026
-- through 31 Mar 2027, the same convention kafalat_package_lines.academic_year
-- already uses as free text — these give it real dates.
CREATE OR REPLACE FUNCTION kafalat_year_starts(p_academic_year varchar) RETURNS date AS $$
  SELECT make_date(split_part(p_academic_year, '-', 1)::int, 4, 1);
$$ LANGUAGE sql IMMUTABLE;

CREATE OR REPLACE FUNCTION kafalat_year_ends(p_academic_year varchar) RETURNS date AS $$
  SELECT (kafalat_year_starts(p_academic_year) + interval '1 year' - interval '1 day')::date;
$$ LANGUAGE sql IMMUTABLE;

CREATE OR REPLACE FUNCTION kafalat_current_year() RETURNS varchar AS $$
  SELECT CASE WHEN extract(month FROM d) >= 4
              THEN extract(year FROM d)::text || '-' || to_char(d + interval '1 year', 'YY')
              ELSE (extract(year FROM d) - 1)::text || '-' || to_char(d, 'YY')
         END
  FROM (SELECT (now() AT TIME ZONE 'Asia/Karachi')::date AS d) x;
$$ LANGUAGE sql STABLE;

-- Months from the later of (joined, year start) through year end, inclusive
-- of the joining month — a child approved on the 30th still needs that
-- month's fee. Floored at 1 so a division never blows up on the year's last
-- day.
CREATE OR REPLACE FUNCTION kafalat_months_remaining(p_academic_year varchar, p_from date DEFAULT NULL)
RETURNS int AS $$
  SELECT GREATEST(
    1,
    (extract(year FROM age(
       date_trunc('month', kafalat_year_ends(p_academic_year)) + interval '1 month',
       date_trunc('month', GREATEST(COALESCE(p_from, (now() AT TIME ZONE 'Asia/Karachi')::date),
                                     kafalat_year_starts(p_academic_year)))
     )) * 12 + extract(month FROM age(
       date_trunc('month', kafalat_year_ends(p_academic_year)) + interval '1 month',
       date_trunc('month', GREATEST(COALESCE(p_from, (now() AT TIME ZONE 'Asia/Karachi')::date),
                                     kafalat_year_starts(p_academic_year)))
     )))::int
  );
$$ LANGUAGE sql STABLE;

-- ═════════════════════════════════════════════════════════════════════════
-- The account itself
-- ═════════════════════════════════════════════════════════════════════════
CREATE OR REPLACE FUNCTION ensure_kafalat_measuring_account(p_academic_year varchar) RETURNS uuid AS $$
DECLARE v_id uuid; v_code varchar;
BEGIN
  v_code := 'KFL-MEASURE-' || split_part(p_academic_year, '-', 1);
  SELECT id INTO v_id FROM accounts WHERE code = v_code AND system = 'donors_projects';
  IF v_id IS NULL THEN
    INSERT INTO accounts (code, name, name_ur, type, system, fund_type, description, is_protected)
    VALUES (v_code, 'Mushtarka Kafalat — Measuring ' || p_academic_year,
            'مشترکہ کفالت — پیمائش ' || p_academic_year,
            'restricted_fund', 'donors_projects', NULL,
            'What every registered child needs for ' || p_academic_year
              || ', against what has been confirmed so far. A requirement register, '
              || 'not a fund — it holds no money and never appears in a trial balance.',
            true)
    RETURNING id INTO v_id;
  END IF;
  RETURN v_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

GRANT EXECUTE ON FUNCTION ensure_kafalat_measuring_account(varchar) TO authenticated;

-- A requirement rising (delta > 0) or falling (delta < 0). A rise debits the
-- account the way a real receivable would; a fall — whether from a confirmed
-- payment or a rate correction — credits it. Both legs land on
-- type=restricted_fund accounts, so migration 221 flags them memo on the way
-- in; nothing here can leak into a trial balance.
CREATE OR REPLACE FUNCTION kafalat_post_requirement_delta(
  p_academic_year varchar, p_delta decimal, p_particular text, p_child_id uuid DEFAULT NULL
) RETURNS void AS $$
DECLARE v_account uuid; v_child_account uuid;
BEGIN
  IF p_delta = 0 THEN RETURN; END IF;
  v_account := ensure_kafalat_measuring_account(p_academic_year);

  INSERT INTO ledger_entries (account_id, entry_date, particular, debit, credit)
  VALUES (v_account, (now() AT TIME ZONE 'Asia/Karachi')::date, p_particular,
          GREATEST(p_delta, 0), GREATEST(-p_delta, 0));

  -- Mirrored onto the child's own account when one exists, so a guardian or
  -- committee member looking at one child sees the same story the year-wide
  -- register tells.
  IF p_child_id IS NOT NULL THEN
    SELECT id INTO v_child_account FROM accounts WHERE kafalat_child_id = p_child_id;
    IF v_child_account IS NOT NULL THEN
      INSERT INTO ledger_entries (account_id, entry_date, particular, debit, credit)
      VALUES (v_child_account, (now() AT TIME ZONE 'Asia/Karachi')::date, p_particular,
              GREATEST(p_delta, 0), GREATEST(-p_delta, 0));
    END IF;
  END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

GRANT EXECUTE ON FUNCTION kafalat_post_requirement_delta(varchar, decimal, text, uuid) TO authenticated;

-- ═════════════════════════════════════════════════════════════════════════
-- The rate card, turned into one child's requirement
-- ═════════════════════════════════════════════════════════════════════════
CREATE OR REPLACE FUNCTION kafalat_generate_requirement(p_child_id uuid, p_academic_year varchar)
RETURNS jsonb AS $$
DECLARE
  c kafalat_children%ROWTYPE;
  v_level int;
  v_tier school_fee_tiers%ROWTYPE;
  v_school_govt boolean := false;
  v_fee_annual decimal := 0;
  v_transport_annual decimal := 0;
  v_uniform decimal; v_books decimal; v_pocket decimal; v_medical decimal; v_exam decimal;
  v_old_total decimal; v_new_total decimal;
  v_prorated_total decimal := 0; v_flat_total decimal := 0;
  v_months int; v_this_year decimal;
BEGIN
  SELECT * INTO c FROM kafalat_children WHERE id = p_child_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Child not found' USING ERRCODE = 'P0001'; END IF;

  v_level := class_to_level(c.current_class);

  -- ── School fee ──────────────────────────────────────────────────────
  IF c.school_id IS NOT NULL THEN
    SELECT (kind = 'government') INTO v_school_govt FROM schools WHERE id = c.school_id;
  END IF;
  IF v_school_govt THEN
    v_fee_annual := 0;
  ELSIF c.school_id IS NOT NULL AND v_level IS NOT NULL THEN
    SELECT * INTO v_tier FROM school_fee_tiers
     WHERE school_id = c.school_id AND v_level BETWEEN class_from AND class_to
     ORDER BY class_from DESC LIMIT 1;
    IF FOUND THEN
      v_fee_annual := v_tier.monthly_fee_pkr * 12 + v_tier.annual_charges_pkr;
    END IF;
  END IF;
  IF v_fee_annual = 0 AND NOT v_school_govt THEN
    -- No school on file yet, or no tier matches the class: fall back to the
    -- village-wide indicative figure so the form is never blank.
    SELECT COALESCE(value::decimal, 0) INTO v_fee_annual
      FROM site_settings WHERE key = 'kafalat_default_school_fee';
  END IF;

  -- ── Transport ───────────────────────────────────────────────────────
  SELECT COALESCE(value::decimal, 0) INTO v_transport_annual FROM site_settings
   WHERE key = CASE c.school_location WHEN 'village' THEN 'kafalat_transport_village'
                                      ELSE 'kafalat_transport_chakwal' END;

  -- ── Once-a-year items, from the rate card ──────────────────────────
  SELECT COALESCE(value::decimal,0) INTO v_uniform FROM site_settings WHERE key='kafalat_default_uniform';
  SELECT COALESCE(value::decimal,0) INTO v_books FROM site_settings WHERE key='kafalat_default_books';
  SELECT COALESCE(value::decimal,0) INTO v_pocket FROM site_settings WHERE key='kafalat_default_pocket_money';
  SELECT COALESCE(value::decimal,0) INTO v_medical FROM site_settings WHERE key='kafalat_default_medical';
  SELECT COALESCE(value::decimal,0) INTO v_exam FROM site_settings WHERE key='kafalat_default_exam_fee';

  -- ── Replace the auto-generated lines; leave manual ones exactly as a
  --    committee member left them ──────────────────────────────────────
  DELETE FROM kafalat_package_lines
   WHERE child_id = p_child_id AND academic_year = p_academic_year AND source = 'auto';

  INSERT INTO kafalat_package_lines (child_id, academic_year, category, description, annual_amount_pkr, is_prorated, source)
  VALUES
    (p_child_id, p_academic_year, 'school_fee', 'School fee (rate card)', v_fee_annual, true, 'auto'),
    (p_child_id, p_academic_year, 'transport', 'Transport (rate card)', v_transport_annual, true, 'auto'),
    (p_child_id, p_academic_year, 'pocket_money', 'Pocket money (rate card)', v_pocket, true, 'auto'),
    (p_child_id, p_academic_year, 'uniform', 'Uniform × 2 (rate card)', v_uniform, false, 'auto'),
    (p_child_id, p_academic_year, 'books', 'Books and stationery (rate card)', v_books, false, 'auto'),
    (p_child_id, p_academic_year, 'medical', 'Medical (rate card)', v_medical, false, 'auto'),
    (p_child_id, p_academic_year, 'exam_fee', 'Exam fee (rate card)', v_exam, false, 'auto');

  -- ── This year's actual requirement: monthly items shrink to what is
  --    left of the year, once-a-year items are charged in full ─────────
  SELECT COALESCE(SUM(annual_amount_pkr) FILTER (WHERE is_prorated), 0),
         COALESCE(SUM(annual_amount_pkr) FILTER (WHERE NOT is_prorated), 0)
    INTO v_prorated_total, v_flat_total
    FROM kafalat_package_lines WHERE child_id = p_child_id AND academic_year = p_academic_year;

  v_months := kafalat_months_remaining(p_academic_year, c.joined_on);
  v_this_year := round(v_prorated_total * v_months / 12.0) + v_flat_total;

  RETURN jsonb_build_object(
    'academic_year', p_academic_year, 'months_remaining', v_months,
    'annual_total', v_prorated_total + v_flat_total, 'this_year_requirement', v_this_year,
    'school_fee_annual', v_fee_annual, 'transport_annual', v_transport_annual,
    'is_govt_school', v_school_govt
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

GRANT EXECUTE ON FUNCTION kafalat_generate_requirement(uuid, varchar) TO authenticated;

-- ── Approving a child properly ────────────────────────────────────────
-- Replaces the admin screen's raw
--     supabase.from('kafalat_children').update({ status: 'active' })
-- which flipped a status and calculated nothing — the same shape of bug
-- fixed in Esal-e-Sawab (migration 225). Approval now runs the rate card and
-- posts the requirement to the measuring account in the same breath, so the
-- pool figure updates the moment the committee says yes.
CREATE OR REPLACE FUNCTION kafalat_approve_child(p_child_id uuid) RETURNS jsonb AS $$
DECLARE
  c kafalat_children%ROWTYPE; v_level int; v_min int; v_max int;
  v_year varchar; v_req jsonb; v_this_year decimal;
BEGIN
  IF NOT COALESCE(current_admin_permission('post_transactions'), false) THEN
    RAISE EXCEPTION 'Not authorized' USING ERRCODE = 'P0001';
  END IF;
  SELECT * INTO c FROM kafalat_children WHERE id = p_child_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Child not found' USING ERRCODE = 'P0001'; END IF;
  IF NOT c.guardian_consent_signed THEN
    RAISE EXCEPTION 'Guardian consent has not been signed yet.' USING ERRCODE = 'P0001';
  END IF;

  v_level := class_to_level(c.current_class);
  SELECT value::int INTO v_min FROM site_settings WHERE key = 'kafalat_min_class';
  SELECT value::int INTO v_max FROM site_settings WHERE key = 'kafalat_max_class';
  IF v_level IS NULL OR v_level < COALESCE(v_min, 1) OR v_level > COALESCE(v_max, 10) THEN
    RAISE EXCEPTION
      'Mushtarka Kafalat covers class % to class %. This child''s class (%) is outside that — for a student past class %, Taleemi Wazifa is the right programme.',
      COALESCE(v_min,1), COALESCE(v_max,10), COALESCE(c.current_class, 'not set'), COALESCE(v_max,10)
      USING ERRCODE = 'P0001';
  END IF;

  v_year := kafalat_current_year();

  UPDATE kafalat_children
     SET status = 'active', joined_on = COALESCE(joined_on, (now() AT TIME ZONE 'Asia/Karachi')::date),
         updated_at = now()
   WHERE id = p_child_id;

  v_req := kafalat_generate_requirement(p_child_id, v_year);
  v_this_year := (v_req->>'this_year_requirement')::decimal;

  PERFORM kafalat_post_requirement_delta(v_year, v_this_year,
    -- Parenthesised deliberately: || and ->> sit at the same precedence and
    -- associate left to right, so without the parens the chain of || runs
    -- first and ->> is left trying to apply to an already-concatenated text
    -- value — "operator does not exist: text ->> unknown". Same trap noted
    -- for %% in plpgsql RAISE strings elsewhere in this codebase; this is
    -- its jsonb sibling.
    c.first_name || ' (' || c.code || ') approved — ' || (v_req->>'months_remaining') || ' months left in ' || v_year,
    p_child_id);

  RETURN v_req || jsonb_build_object('child_code', c.code);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE ALL ON FUNCTION kafalat_approve_child(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION kafalat_approve_child(uuid) TO authenticated;

-- Ending a sponsorship removes what was left of this year's requirement —
-- the committee should not keep being measured against a child who left the
-- village or graduated mid-year.
CREATE OR REPLACE FUNCTION kafalat_end_child(p_child_id uuid, p_status varchar, p_reason text DEFAULT NULL)
RETURNS jsonb AS $$
DECLARE c kafalat_children%ROWTYPE; v_year varchar; v_req jsonb;
BEGIN
  IF NOT COALESCE(current_admin_permission('post_transactions'), false) THEN
    RAISE EXCEPTION 'Not authorized' USING ERRCODE = 'P0001';
  END IF;
  IF p_status NOT IN ('graduated', 'withdrawn', 'left_village') THEN
    RAISE EXCEPTION 'Not a valid ending status.' USING ERRCODE = 'P0001';
  END IF;
  SELECT * INTO c FROM kafalat_children WHERE id = p_child_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Child not found' USING ERRCODE = 'P0001'; END IF;

  v_year := kafalat_current_year();
  IF c.status = 'active' THEN
    -- Undo whatever this year's requirement had added, then delete the
    -- current year's auto lines so a re-approval later starts clean.
    v_req := kafalat_generate_requirement(p_child_id, v_year);
    PERFORM kafalat_post_requirement_delta(v_year, -(v_req->>'this_year_requirement')::decimal,
      c.first_name || ' (' || c.code || ') — sponsorship ended: ' || p_status, p_child_id);
    DELETE FROM kafalat_package_lines WHERE child_id = p_child_id AND academic_year = v_year AND source = 'auto';
  END IF;

  UPDATE kafalat_children
     SET status = p_status, ended_on = (now() AT TIME ZONE 'Asia/Karachi')::date,
         ended_reason = p_reason, updated_at = now()
   WHERE id = p_child_id;

  RETURN jsonb_build_object('ok', true, 'status', p_status);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE ALL ON FUNCTION kafalat_end_child(uuid, varchar, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION kafalat_end_child(uuid, varchar, text) TO authenticated;

-- ── The register itself, readable in one call ─────────────────────────
CREATE OR REPLACE FUNCTION kafalat_measuring_position(p_academic_year varchar DEFAULT NULL)
RETURNS jsonb AS $$
DECLARE
  v_year varchar; v_account uuid; v_required decimal; v_confirmed decimal;
  v_outstanding decimal; v_months int; v_monthly decimal; v_children int;
BEGIN
  v_year := COALESCE(p_academic_year, kafalat_current_year());
  v_account := ensure_kafalat_measuring_account(v_year);

  SELECT COALESCE(SUM(debit),0), COALESCE(SUM(credit),0)
    INTO v_required, v_confirmed FROM ledger_entries WHERE account_id = v_account;
  v_outstanding := GREATEST(v_required - v_confirmed, 0);
  v_months := kafalat_months_remaining(v_year);
  v_monthly := round(v_outstanding / v_months);
  SELECT count(*) INTO v_children FROM kafalat_children WHERE status = 'active';

  RETURN jsonb_build_object(
    'academic_year', v_year, 'account_code', 'KFL-MEASURE-' || split_part(v_year,'-',1),
    'required', v_required, 'confirmed', v_confirmed, 'outstanding', v_outstanding,
    'months_remaining', v_months, 'monthly_target', v_monthly, 'children_active', v_children,
    'year_starts', kafalat_year_starts(v_year), 'year_ends', kafalat_year_ends(v_year)
  );
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public;

GRANT EXECUTE ON FUNCTION kafalat_measuring_position(varchar) TO authenticated, anon;

-- ═════════════════════════════════════════════════════════════════════════
-- The pool now reads the measuring account instead of recomputing blind
-- ═════════════════════════════════════════════════════════════════════════
-- The old kind='kafalat' branch summed every active child's full annual
-- package and divided by twelve regardless of the date or what had already
-- been raised. This reads what is actually still owed for the rest of THIS
-- year, divided by the months actually left in it — the figure genuinely
-- falls as donors are confirmed, and genuinely reflects a mid-year approval.
CREATE OR REPLACE FUNCTION pool_monthly_target(p_pool_id uuid) RETURNS decimal AS $$
DECLARE p support_pools%ROWTYPE; v decimal;
BEGIN
  SELECT * INTO p FROM support_pools WHERE id = p_pool_id;
  IF NOT FOUND THEN RETURN 0; END IF;
  IF p.manual_monthly_target_pkr IS NOT NULL THEN RETURN p.manual_monthly_target_pkr; END IF;

  IF p.kind = 'kafalat' THEN
    v := (kafalat_measuring_position()->>'monthly_target')::decimal;
  ELSIF p.kind = 'wazifa' THEN
    SELECT COALESCE(SUM(a.awarded_amount_pkr), 0) / 12
      INTO v FROM wazifa_awards a WHERE a.status = 'active';
  ELSIF p.kind = 'project' AND p.project_id IS NOT NULL THEN
    SELECT COALESCE(monthly_operating_cost_pkr, 0) INTO v FROM projects WHERE id = p.project_id;
  ELSE
    v := 0;
  END IF;
  RETURN COALESCE(round(v), 0);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public;
