-- Migration 232: the paper the committee actually hands to a school and a
-- driver — roll numbers, uniforms, transport, and the disbursements that pay
-- for them.
--
-- ═════════════════════════════════════════════════════════════════════════
-- What this adds, and what it deliberately leaves alone
-- ═════════════════════════════════════════════════════════════════════════
-- The measuring account (migration 230) answers "how much do we still need
-- this year, and from how many donors". It never answers "which school, which
-- roll number, has this term's uniform gone out yet" — that is a different
-- axis of the same programme, and it is what a committee member actually
-- carries to a school gate or hands to a driver.
--
-- Two disbursement rhythms, because they are genuinely different:
--
--   Uniform — twice a year, not monthly. The committee decides per child
--   whether both go out together at the start of the year, staggered six
--   months apart (a growing child, a uniform that is still whole in March),
--   or paid as cash directly to the guardian, who buys it themselves. The
--   schedule is generated once, at approval, from that choice.
--
--   Transport and pocket money — monthly, for as long as the child is
--   active, generated by a scheduled job the same way sadqa_upkeep_run() and
--   pool_announce_recurring_month() already generate theirs.
--
-- Both post through the 'kafalat_payment' voucher type migration 218 already
-- reserved for exactly this and never used — the ring-fencing, the numbering,
-- the per-child subsidiary ledger (ensure_kafalat_child_account) were all
-- already built, waiting for a real caller. This is deliberately a SEPARATE
-- ledger dimension from the measuring account: the measuring account tracks
-- whether donors have raised enough; this tracks what was actually spent on
-- one named child. A committee should be able to answer both "are we short
-- this year" and "what has Bilal actually received" without one figure
-- standing in for the other.

ALTER TABLE kafalat_children
  ADD COLUMN IF NOT EXISTS roll_no varchar,
  ADD COLUMN IF NOT EXISTS section varchar,
  -- both       — two uniforms handed over together, once, at the start
  -- staggered  — one now, the second six months later
  -- cash       — money to the guardian instead of a physical item; they buy it
  ADD COLUMN IF NOT EXISTS uniform_mode varchar NOT NULL DEFAULT 'staggered'
    CHECK (uniform_mode IN ('both', 'staggered', 'cash'));

-- ═════════════════════════════════════════════════════════════════════════
-- Uniforms
-- ═════════════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS kafalat_uniform_issues (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  child_id uuid NOT NULL REFERENCES kafalat_children(id) ON DELETE CASCADE,
  academic_year varchar NOT NULL,
  -- 1 or 2 — which of the year's two uniforms this is.
  issue_no int NOT NULL CHECK (issue_no IN (1, 2)),
  scheduled_on date NOT NULL,
  amount_pkr decimal NOT NULL DEFAULT 0 CHECK (amount_pkr >= 0),
  status varchar NOT NULL DEFAULT 'scheduled'
    CHECK (status IN ('scheduled', 'issued', 'skipped')),
  issued_on date,
  -- A physical item at the school gate, or cash into the guardian's hand —
  -- either way, somebody's name goes down as having received it. Not a
  -- digital signature; a record that the paper form was signed, the same
  -- convention this codebase already uses for verifiers (co_verifier_names).
  received_by varchar,
  signed_note text,
  voucher_id uuid REFERENCES vouchers(id) ON DELETE SET NULL,
  skipped_reason text,
  created_at timestamptz DEFAULT now(),
  UNIQUE (child_id, academic_year, issue_no)
);

CREATE INDEX IF NOT EXISTS kafalat_uniform_status_idx ON kafalat_uniform_issues(status, scheduled_on);

-- Built once, at approval, from the committee's choice for this child. Not a
-- scheduled job — a child does not get a new uniform schedule every day, only
-- once a year (and kafalat_approve_child already regenerates the requirement
-- on re-approval, which is the natural place to regenerate this alongside it).
CREATE OR REPLACE FUNCTION kafalat_schedule_uniforms(p_child_id uuid, p_academic_year varchar)
RETURNS void AS $$
DECLARE
  c kafalat_children%ROWTYPE; v_amount decimal; v_start date;
BEGIN
  SELECT * INTO c FROM kafalat_children WHERE id = p_child_id;
  IF NOT FOUND THEN RETURN; END IF;

  SELECT COALESCE(SUM(annual_amount_pkr), 0) / 2 INTO v_amount
    FROM kafalat_package_lines
   WHERE child_id = p_child_id AND academic_year = p_academic_year AND category = 'uniform';
  IF v_amount <= 0 THEN RETURN; END IF;

  v_start := GREATEST(COALESCE(c.joined_on, kafalat_year_starts(p_academic_year)),
                      kafalat_year_starts(p_academic_year));

  -- Regenerating must not lose a uniform that has already gone out — only the
  -- still-scheduled ones are replaced.
  DELETE FROM kafalat_uniform_issues
   WHERE child_id = p_child_id AND academic_year = p_academic_year AND status = 'scheduled';

  IF c.uniform_mode = 'both' THEN
    INSERT INTO kafalat_uniform_issues (child_id, academic_year, issue_no, scheduled_on, amount_pkr)
    VALUES (p_child_id, p_academic_year, 1, v_start, v_amount),
           (p_child_id, p_academic_year, 2, v_start, v_amount)
    ON CONFLICT (child_id, academic_year, issue_no) DO NOTHING;
  ELSE
    -- 'staggered' and 'cash' both run on the same six-month rhythm; 'cash'
    -- only changes how the second half of this function pays it out.
    INSERT INTO kafalat_uniform_issues (child_id, academic_year, issue_no, scheduled_on, amount_pkr)
    VALUES (p_child_id, p_academic_year, 1, v_start, v_amount),
           (p_child_id, p_academic_year, 2, (v_start + interval '6 months')::date, v_amount)
    ON CONFLICT (child_id, academic_year, issue_no) DO NOTHING;
  END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

GRANT EXECUTE ON FUNCTION kafalat_schedule_uniforms(uuid, varchar) TO authenticated;

-- Folded into approval and re-approval, so the uniform schedule is never a
-- separate step somebody has to remember.
CREATE OR REPLACE FUNCTION kafalat_approve_child(p_child_id uuid) RETURNS jsonb AS $$
DECLARE
  c kafalat_children%ROWTYPE; v_level int; v_min int; v_max int;
  v_year varchar; v_req jsonb; v_this_year decimal;
BEGIN
  IF NOT COALESCE(current_admin_permission('post_transactions'), false) THEN
    RAISE EXCEPTION 'Not authorized' USING ERRCODE = 'P0001';
  END IF;
  SELECT * INTO c FROM kafalat_children WHERE id = p_child_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Child not found' USING ERRCODE = 'P0001'; END IF;
  IF NOT c.guardian_consent_signed THEN
    RAISE EXCEPTION 'Guardian consent has not been signed yet.' USING ERRCODE = 'P0001';
  END IF;

  v_level := class_to_level(c.current_class);
  SELECT value::int INTO v_min FROM site_settings WHERE key = 'kafalat_min_class';
  SELECT value::int INTO v_max FROM site_settings WHERE key = 'kafalat_max_class';
  IF v_level IS NULL OR v_level < COALESCE(v_min, 1) OR v_level > COALESCE(v_max, 10) THEN
    RAISE EXCEPTION
      'Mushtarka Kafalat covers class % to class %. This child''s class (%) is outside that — for a student past class %, Taleemi Wazifa is the right programme.',
      COALESCE(v_min,1), COALESCE(v_max,10), COALESCE(c.current_class, 'not set'), COALESCE(v_max,10)
      USING ERRCODE = 'P0001';
  END IF;

  v_year := kafalat_current_year();

  UPDATE kafalat_children
     SET status = 'active', joined_on = COALESCE(joined_on, (now() AT TIME ZONE 'Asia/Karachi')::date),
         updated_at = now()
   WHERE id = p_child_id;

  v_req := kafalat_generate_requirement(p_child_id, v_year);
  v_this_year := (v_req->>'this_year_requirement')::decimal;

  PERFORM kafalat_post_requirement_delta(v_year, v_this_year,
    c.first_name || ' (' || c.code || ') approved — ' || (v_req->>'months_remaining') || ' months left in ' || v_year,
    p_child_id);

  PERFORM kafalat_schedule_uniforms(p_child_id, v_year);

  RETURN v_req || jsonb_build_object('child_code', c.code);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- Handing one over — a physical item at the school gate, or cash to the
-- guardian if that is what the committee chose for this child.
CREATE OR REPLACE FUNCTION kafalat_issue_uniform(
  p_issue_id uuid, p_received_by varchar, p_signed_note text DEFAULT NULL, p_method varchar DEFAULT 'cash'
) RETURNS jsonb AS $$
DECLARE
  u kafalat_uniform_issues%ROWTYPE; c kafalat_children%ROWTYPE;
  v_cash uuid; v_child_account uuid; v_voucher_id uuid; v_voucher_no varchar;
BEGIN
  IF NOT COALESCE(current_admin_permission('post_transactions'), false) THEN
    RAISE EXCEPTION 'Not authorized' USING ERRCODE = 'P0001';
  END IF;
  SELECT * INTO u FROM kafalat_uniform_issues WHERE id = p_issue_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Not found' USING ERRCODE = 'P0001'; END IF;
  IF u.status <> 'scheduled' THEN
    RAISE EXCEPTION 'This uniform is already %.', u.status USING ERRCODE = 'P0001';
  END IF;
  IF COALESCE(trim(p_received_by), '') = '' THEN
    RAISE EXCEPTION 'Name whoever received it — the child, the guardian, or the shop.'
      USING ERRCODE = 'P0001';
  END IF;
  SELECT * INTO c FROM kafalat_children WHERE id = u.child_id;

  SELECT id INTO v_cash FROM accounts WHERE system = 'donors_projects'
     AND code = (CASE WHEN p_method = 'cash' THEN 'DP-1001' ELSE 'DP-1002' END);

  INSERT INTO vouchers (system, voucher_type, voucher_date, particular, amount_pkr,
    from_account_id, to_account_id, party_name, kafalat_child_id, fund_type)
  VALUES ('donors_projects', 'kafalat_payment', (now() AT TIME ZONE 'Asia/Karachi')::date,
    c.first_name || ' (' || c.code || ') — uniform ' || u.issue_no || '/2, ' || u.academic_year
      || CASE WHEN c.uniform_mode = 'cash' THEN ' (cash to guardian)' ELSE '' END,
    u.amount_pkr, v_cash, v_cash, c.first_name, u.child_id, 'kafalat')
  RETURNING id, voucher_no INTO v_voucher_id, v_voucher_no;

  UPDATE kafalat_uniform_issues
     SET status = 'issued', issued_on = (now() AT TIME ZONE 'Asia/Karachi')::date,
         received_by = p_received_by, signed_note = p_signed_note, voucher_id = v_voucher_id
   WHERE id = p_issue_id;

  RETURN jsonb_build_object('voucher_no', v_voucher_no, 'amount', u.amount_pkr);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE ALL ON FUNCTION kafalat_issue_uniform(uuid, varchar, text, varchar) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION kafalat_issue_uniform(uuid, varchar, text, varchar) TO authenticated;

CREATE OR REPLACE FUNCTION kafalat_skip_uniform(p_issue_id uuid, p_reason text) RETURNS jsonb AS $$
BEGIN
  IF NOT COALESCE(current_admin_permission('post_transactions'), false) THEN
    RAISE EXCEPTION 'Not authorized' USING ERRCODE = 'P0001';
  END IF;
  UPDATE kafalat_uniform_issues SET status = 'skipped', skipped_reason = p_reason
   WHERE id = p_issue_id AND status = 'scheduled';
  IF NOT FOUND THEN RAISE EXCEPTION 'Not found or already resolved.' USING ERRCODE = 'P0001'; END IF;
  RETURN jsonb_build_object('ok', true);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE ALL ON FUNCTION kafalat_skip_uniform(uuid, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION kafalat_skip_uniform(uuid, text) TO authenticated;

-- ═════════════════════════════════════════════════════════════════════════
-- Transport and pocket money — monthly, for as long as the child is active
-- ═════════════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS kafalat_disbursements (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  child_id uuid NOT NULL REFERENCES kafalat_children(id) ON DELETE CASCADE,
  category varchar NOT NULL CHECK (category IN ('transport', 'pocket_money')),
  month date NOT NULL,
  amount_pkr decimal NOT NULL CHECK (amount_pkr > 0),
  status varchar NOT NULL DEFAULT 'scheduled'
    CHECK (status IN ('scheduled', 'paid', 'skipped')),
  -- Who the money actually goes to. Transport is usually the driver, though a
  -- guardian who does the school run themselves is paid the same way; pocket
  -- money is always the guardian.
  recipient varchar NOT NULL DEFAULT 'guardian' CHECK (recipient IN ('guardian', 'driver', 'student')),
  driver_name varchar,
  paid_on date,
  method varchar CHECK (method IN ('cash', 'bank', 'jazzcash', 'easypaisa')),
  -- The paper record of a signature, not a digital one — same convention as
  -- the uniform table above.
  signed_by varchar,
  signed_note text,
  voucher_id uuid REFERENCES vouchers(id) ON DELETE SET NULL,
  skipped_reason text,
  created_at timestamptz DEFAULT now(),
  UNIQUE (child_id, category, month)
);

CREATE INDEX IF NOT EXISTS kafalat_disbursements_status_idx ON kafalat_disbursements(status, month);

-- Raises this month's transport and pocket-money lines for every active
-- child who has them in their package, the same idempotent shape as
-- sadqa_upkeep_run() and pool_announce_recurring_month().
CREATE OR REPLACE FUNCTION kafalat_disbursement_run() RETURNS jsonb AS $$
DECLARE v_month date; v_year varchar; v_count int;
BEGIN
  v_month := date_trunc('month', (now() AT TIME ZONE 'Asia/Karachi')::date)::date;
  v_year := kafalat_current_year();

  INSERT INTO kafalat_disbursements (child_id, category, month, amount_pkr, recipient)
  SELECT c.id, l.category, v_month, round(l.annual_amount_pkr / 12.0),
         CASE WHEN l.category = 'transport' THEN 'driver' ELSE 'guardian' END
    FROM kafalat_children c
    JOIN kafalat_package_lines l ON l.child_id = c.id AND l.academic_year = v_year
   WHERE c.status = 'active'
     AND l.category IN ('transport', 'pocket_money')
     AND l.annual_amount_pkr > 0
     AND NOT EXISTS (SELECT 1 FROM kafalat_disbursements d
                      WHERE d.child_id = c.id AND d.category = l.category AND d.month = v_month);
  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN jsonb_build_object('created', v_count, 'month', v_month);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE ALL ON FUNCTION kafalat_disbursement_run() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION kafalat_disbursement_run() TO authenticated;

DO $$
BEGIN
  PERFORM cron.schedule('kafalat-disbursement-run', '10 4 * * *', 'SELECT kafalat_disbursement_run()');
  RAISE NOTICE 'pg_cron: kafalat transport/pocket-money lines raised daily at 09:10 PKT';
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'pg_cron unavailable — run kafalat_disbursement_run() from the Kafalat screen. %', SQLERRM;
END $$;

CREATE OR REPLACE FUNCTION kafalat_pay_disbursement(
  p_disbursement_id uuid, p_method varchar, p_signed_by varchar DEFAULT NULL,
  p_driver_name varchar DEFAULT NULL, p_signed_note text DEFAULT NULL
) RETURNS jsonb AS $$
DECLARE
  d kafalat_disbursements%ROWTYPE; c kafalat_children%ROWTYPE;
  v_cash uuid; v_voucher_id uuid; v_voucher_no varchar;
BEGIN
  IF NOT COALESCE(current_admin_permission('post_transactions'), false) THEN
    RAISE EXCEPTION 'Not authorized' USING ERRCODE = 'P0001';
  END IF;
  SELECT * INTO d FROM kafalat_disbursements WHERE id = p_disbursement_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Not found' USING ERRCODE = 'P0001'; END IF;
  IF d.status <> 'scheduled' THEN
    RAISE EXCEPTION 'This is already %.', d.status USING ERRCODE = 'P0001';
  END IF;
  IF d.category = 'transport' AND COALESCE(trim(p_driver_name), '') = '' THEN
    RAISE EXCEPTION 'Name the driver this transport payment is going to.' USING ERRCODE = 'P0001';
  END IF;
  SELECT * INTO c FROM kafalat_children WHERE id = d.child_id;

  SELECT id INTO v_cash FROM accounts WHERE system = 'donors_projects'
     AND code = (CASE WHEN p_method = 'cash' THEN 'DP-1001' ELSE 'DP-1002' END);

  INSERT INTO vouchers (system, voucher_type, voucher_date, particular, amount_pkr,
    from_account_id, to_account_id, party_name, kafalat_child_id, fund_type)
  VALUES ('donors_projects', 'kafalat_payment', (now() AT TIME ZONE 'Asia/Karachi')::date,
    c.first_name || ' (' || c.code || ') — ' || d.category || ' · ' || to_char(d.month, 'Mon YYYY')
      || CASE WHEN d.category = 'transport' THEN ' · driver ' || p_driver_name ELSE '' END,
    d.amount_pkr, v_cash, v_cash,
    CASE WHEN d.category = 'transport' THEN p_driver_name ELSE c.guardian_name END,
    d.child_id, 'kafalat')
  RETURNING id, voucher_no INTO v_voucher_id, v_voucher_no;

  UPDATE kafalat_disbursements
     SET status = 'paid', paid_on = (now() AT TIME ZONE 'Asia/Karachi')::date, method = p_method,
         signed_by = p_signed_by, driver_name = COALESCE(p_driver_name, driver_name),
         signed_note = p_signed_note, voucher_id = v_voucher_id
   WHERE id = p_disbursement_id;

  RETURN jsonb_build_object('voucher_no', v_voucher_no, 'amount', d.amount_pkr);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE ALL ON FUNCTION kafalat_pay_disbursement(uuid, varchar, varchar, varchar, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION kafalat_pay_disbursement(uuid, varchar, varchar, varchar, text) TO authenticated;

CREATE OR REPLACE FUNCTION kafalat_skip_disbursement(p_disbursement_id uuid, p_reason text) RETURNS jsonb AS $$
BEGIN
  IF NOT COALESCE(current_admin_permission('post_transactions'), false) THEN
    RAISE EXCEPTION 'Not authorized' USING ERRCODE = 'P0001';
  END IF;
  UPDATE kafalat_disbursements SET status = 'skipped', skipped_reason = p_reason
   WHERE id = p_disbursement_id AND status = 'scheduled';
  IF NOT FOUND THEN RAISE EXCEPTION 'Not found or already resolved.' USING ERRCODE = 'P0001'; END IF;
  RETURN jsonb_build_object('ok', true);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE ALL ON FUNCTION kafalat_skip_disbursement(uuid, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION kafalat_skip_disbursement(uuid, text) TO authenticated;

-- What is due right now, across both uniforms and monthly disbursements —
-- the one queue the accountant actually works from.
CREATE OR REPLACE FUNCTION kafalat_disbursement_queue() RETURNS jsonb AS $$
  SELECT jsonb_build_object(
    'uniforms', COALESCE((
      SELECT jsonb_agg(jsonb_build_object(
        'id', u.id, 'child_code', c.code, 'child_name', c.first_name, 'guardian', c.guardian_name,
        'guardian_phone', c.guardian_phone, 'issue_no', u.issue_no, 'scheduled_on', u.scheduled_on,
        'amount', u.amount_pkr, 'uniform_mode', c.uniform_mode
      ) ORDER BY u.scheduled_on)
        FROM kafalat_uniform_issues u JOIN kafalat_children c ON c.id = u.child_id
       WHERE u.status = 'scheduled' AND u.scheduled_on <= (now() AT TIME ZONE 'Asia/Karachi')::date
    ), '[]'::jsonb),
    'disbursements', COALESCE((
      SELECT jsonb_agg(jsonb_build_object(
        'id', d.id, 'child_code', c.code, 'child_name', c.first_name, 'guardian', c.guardian_name,
        'guardian_phone', c.guardian_phone, 'category', d.category, 'month', d.month, 'amount', d.amount_pkr
      ) ORDER BY d.month, d.category)
        FROM kafalat_disbursements d JOIN kafalat_children c ON c.id = d.child_id
       WHERE d.status = 'scheduled'
    ), '[]'::jsonb)
  );
$$ LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public;

REVOKE ALL ON FUNCTION kafalat_disbursement_queue() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION kafalat_disbursement_queue() TO authenticated;

-- ═════════════════════════════════════════════════════════════════════════
-- The register — what a committee member actually prints
-- ═════════════════════════════════════════════════════════════════════════
-- Every active child, their school, roll number, class, fee, when it is next
-- due, and the transport line with a blank for the driver's signature. This
-- is a document meant for paper, not a dashboard — it is built to be printed
-- and carried, the same way the Wazifa verification sheet is.
CREATE OR REPLACE FUNCTION kafalat_register(p_academic_year varchar DEFAULT NULL) RETURNS jsonb AS $$
DECLARE v_year varchar;
BEGIN
  v_year := COALESCE(p_academic_year, kafalat_current_year());
  RETURN jsonb_build_object(
    'academic_year', v_year,
    'generated_at', now(),
    'children', COALESCE((
      SELECT jsonb_agg(jsonb_build_object(
        'code', c.code, 'name', c.first_name, 'guardian', c.guardian_name,
        'guardian_phone', c.guardian_phone, 'roll_no', c.roll_no, 'section', c.section,
        'current_class', c.current_class,
        'school_name', COALESCE(s.name, c.school_name), 'school_location', c.school_location,
        'school_fee_monthly', COALESCE(t.monthly_fee_pkr, 0),
        'fee_annual', COALESCE((SELECT annual_amount_pkr FROM kafalat_package_lines
                                  WHERE child_id = c.id AND academic_year = v_year AND category = 'school_fee'), 0),
        'transport_annual', COALESCE((SELECT annual_amount_pkr FROM kafalat_package_lines
                                       WHERE child_id = c.id AND academic_year = v_year AND category = 'transport'), 0),
        'fee_next_due_on', (date_trunc('month', (now() AT TIME ZONE 'Asia/Karachi')::date)
                             + interval '1 month' - interval '1 day')::date,
        'uniform_mode', c.uniform_mode,
        'uniform_status', (
          SELECT jsonb_agg(jsonb_build_object('issue_no', u.issue_no, 'status', u.status,
                                              'scheduled_on', u.scheduled_on) ORDER BY u.issue_no)
            FROM kafalat_uniform_issues u WHERE u.child_id = c.id AND u.academic_year = v_year
        )
      ) ORDER BY c.code)
        FROM kafalat_children c
        LEFT JOIN schools s ON s.id = c.school_id
        LEFT JOIN school_fee_tiers t ON t.school_id = c.school_id
          AND class_to_level(c.current_class) BETWEEN t.class_from AND t.class_to
       WHERE c.status = 'active'
    ), '[]'::jsonb)
  );
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public;

GRANT EXECUTE ON FUNCTION kafalat_register(varchar) TO authenticated;

-- ── Permissions ──────────────────────────────────────────────────────────
-- Staff-only, same as kafalat_children itself — nothing here is ever shown
-- to a donor or a guardian's own portal.
ALTER TABLE kafalat_uniform_issues ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS kafalat_uniform_issues_admin ON kafalat_uniform_issues;
CREATE POLICY kafalat_uniform_issues_admin ON kafalat_uniform_issues FOR ALL TO authenticated
  USING (can_access_system('donors_projects')) WITH CHECK (can_access_system('donors_projects'));
REVOKE ALL ON kafalat_uniform_issues FROM anon;

ALTER TABLE kafalat_disbursements ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS kafalat_disbursements_admin ON kafalat_disbursements;
CREATE POLICY kafalat_disbursements_admin ON kafalat_disbursements FOR ALL TO authenticated
  USING (can_access_system('donors_projects')) WITH CHECK (can_access_system('donors_projects'));
REVOKE ALL ON kafalat_disbursements FROM anon;

-- ═════════════════════════════════════════════════════════════════════════
-- Fixing a collision waiting to happen: ensure_kafalat_child_account()
-- ═════════════════════════════════════════════════════════════════════════
-- migration 218 built this and nothing had ever called it — kafalat_payment
-- vouchers were reserved but unused until this migration wires real uniform
-- and disbursement payments through them. Driving it for the first time
-- surfaced the bug: the account code was built from the first eight hex
-- characters of the child's UUID —
--
--     'KID-' || substr(replace(p_child_id::text, '-', ''), 1, 8)
--
-- — thirty-two bits of a randomly generated identifier, while the function
-- had already fetched the child's real code (kafalat_children.code, unique
-- by a real sequence, next_kafalat_code()) into a variable and used it only
-- for the account's display NAME. Two children's UUIDs sharing their first
-- eight hex characters produce the same account code and the second child's
-- INSERT fails outright — accounts.code is unique. Confirmed empirically: a
-- handful of test children were enough to collide.
--
-- No live data is affected — nothing had posted a kafalat_payment voucher
-- before this migration, so no 'KID-' account exists yet to repair.
CREATE OR REPLACE FUNCTION ensure_kafalat_child_account(p_child_id uuid) RETURNS uuid AS $$
DECLARE v_id uuid; v_code varchar;
BEGIN
  SELECT id INTO v_id FROM accounts WHERE kafalat_child_id = p_child_id;
  IF v_id IS NOT NULL THEN RETURN v_id; END IF;
  SELECT code INTO v_code FROM kafalat_children WHERE id = p_child_id;
  INSERT INTO accounts (code, name, type, system, kafalat_child_id, opening_balance)
  VALUES ('KID-' || COALESCE(v_code, replace(p_child_id::text, '-', '')),
          COALESCE(v_code, 'Child'), 'student', 'donors_projects', p_child_id, 0)
  RETURNING id INTO v_id;
  RETURN v_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

GRANT EXECUTE ON FUNCTION ensure_kafalat_child_account(uuid) TO authenticated;
